import {useOverviewData} from './useOverviewData.js';
import {pnlSummary,rValue,moneyCurrency,sourceLabel} from '../journal/journalUtils';
import {SeriesChart} from '../../components/insights/MetricCharts.jsx';
export default function DashboardPage({onNavigate}) {
  const {data,errors}=useOverviewData(),summary=data.journal?.summary||{},runs=data.runs?.runs||[],jobs=data.jobs?.jobs||[],active=jobs.filter(j=>['running','preparing data','queued'].includes(j.status));
  const entries=[...(data.journal?.trades||[]).slice(0,5).map(t=>({key:`t${t.id}`,date:t.updated_at||t.imported_at||t.opened_at,label:`${t.ticker} · ${sourceLabel(t.source)} · ${rValue(t.r_multiple)}`,page:'Journal'})),...runs.slice(0,5).map(r=>({key:`r${r.id}`,date:r.created_at,label:`Backtest #${r.id} · ${r.name||r.strategy_name}`,page:'Backtest'}))].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,8);
  return <div className="dense-page space-y-6"><div><p className="muted text-xs uppercase tracking-widest">Ledger</p><h2 className="text-3xl font-semibold mt-1">Overview</h2><p className="muted text-sm mt-2">Your trading, investments and research at a glance.</p></div>{errors.map(e=><p key={e} role="status" className="muted text-xs">{e}. Showing the last available snapshot where possible.</p>)}
    <section><div className="ui-toolbar"><h3 className="font-semibold">Trading · last 30 calendar days</h3><span className="muted text-xs">{data.period}</span><button className="mini-btn" onClick={()=>onNavigate('Journal')}>Open Journal</button></div><dl className="primary-metrics">{[['Net P&L',pnlSummary(summary)],['Total R',rValue(summary.total_r)],['Expectancy',rValue(summary.average_r)],['Trades',summary.trades??'Unavailable']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="muted text-xs">R drawdown {rValue(summary.max_drawdown_r)} · R sample N={summary.r_trades??0}. Results include the sources recorded in Journal; detailed filtering is available there.</p></section>
    <div className="insight-grid"><SeriesChart title="Recent cumulative R" points={data.journal?.r_curve||[]} valueKey="cumulative_r" description="Recorded closed Journal trades."/><section className="insight-panel"><div className="ui-toolbar"><h4>Investments</h4><button className="mini-btn" onClick={()=>onNavigate('Investment Portfolio')}>Open Portfolio</button></div>{!(data.accounts?.items||[]).length?<p className="empty-state">No broker investment snapshot yet.</p>:(data.accounts.items).map(a=><div key={a.account_key} className="overview-account"><strong>{a.label}</strong><dl><div><dt>Value</dt><dd>{moneyCurrency(a.summary?.totalValue,a.summary?.currency)}</dd></div><div><dt>Unrealised P&L</dt><dd>{moneyCurrency(a.summary?.investments?.unrealizedProfitLoss,a.summary?.currency)}</dd></div><div><dt>Cash</dt><dd>{moneyCurrency(a.summary?.cash?.availableToTrade,a.summary?.currency)}</dd></div></dl></div>)}<p className="muted text-xs">Accounts and currencies stay separate. Values reflect the last successful sync.</p></section></div>
    <div className="insight-grid"><section className="insight-panel"><div className="ui-toolbar"><h4>Research</h4><button className="mini-btn" onClick={()=>onNavigate('Backtest')}>Open Backtest</button></div><p className="mt-3 text-sm">{active.length} active / queued jobs · {jobs.filter(j=>j.status==='failed').length} failed jobs</p>{active.slice(0,4).map(j=><p className="mt-2 text-xs" key={j.id}>{j.payload.symbols.join(', ')} · {j.status}{j.total?` · ${Math.floor(100*j.processed/j.total)}%`:''}</p>)}<h4 className="mt-4">Recently completed runs</h4>{runs.slice(0,4).map(r=><button className="overview-activity" key={r.id} onClick={()=>onNavigate('Backtest')}>#{r.id} {r.name||r.strategy_name}<small>{r.test_role?.replaceAll('_',' ')} · N={r.trades}</small></button>)}</section><section className="insight-panel"><h4>Recent activity</h4>{entries.map(e=><button className="overview-activity" key={e.key} onClick={()=>onNavigate(e.page)}>{e.label}<small>{e.date?.slice(0,16).replace('T',' ')}</small></button>)}{!entries.length&&<p className="empty-state">Completed research and recorded trades will appear here.</p>}</section></div>
  </div>;
}
