import {useState} from 'react';
import {useUIPreference} from '../../app/useUIPreference.js';
export function templateValue({settings,timeframe,session,indicators}){return {settings:{...settings},timeframe,session,indicators:indicators.map(({id,...rest})=>structuredClone(rest))};}
export default function ChartSettings({settings,onChange,timeframe,session,indicators,onApply}){
 const [templates,setTemplates]=useUIPreference('chart.templates',[]),[name,setName]=useState(''),[selected,setSelected]=useState('');
 return <details className="chart-settings"><summary className="chart-toolbar-btn">Chart settings / templates</summary><div className="insight-panel space-y-3">
 <div className="ui-toolbar">{[['chartGridVisible','Grid'],['chartVolumeVisible','Volume'],['chartCrosshair','Crosshair'],['chartAutoScale','Auto scale']].map(([key,label])=><label key={key}><input type="checkbox" checked={settings[key]!==false} onChange={e=>onChange({...settings,[key]:e.target.checked})}/> {label}</label>)}<label>Initial visible bars <input type="number" min="60" max="2000" className="input table-density" value={settings.chartVisibleBars||180} onChange={e=>onChange({...settings,chartVisibleBars:Math.max(60,Math.min(2000,Number(e.target.value)||180))})}/></label></div>
 <div className="ui-toolbar"><input aria-label="Chart template name" className="input table-search" placeholder="Template name" value={name} onChange={e=>setName(e.target.value)}/><button className="mini-btn" disabled={!name.trim()} onClick={()=>{setTemplates([...templates.filter(t=>t.name!==name.trim()),{name:name.trim(),...templateValue({settings,timeframe,session,indicators})}]);setSelected(name.trim());}}>Save template</button><select aria-label="Chart template" className="input table-density" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select template</option>{templates.map(t=><option key={t.name}>{t.name}</option>)}</select><button className="mini-btn" disabled={!selected} onClick={()=>onApply(templates.find(t=>t.name===selected))}>Apply template</button><button className="mini-btn" disabled={!selected} onClick={()=>{setTemplates(templates.filter(t=>t.name!==selected));setSelected('');}}>Delete template</button></div><p className="muted text-xs">Templates include chart options, timeframe, session and indicators. Symbols and drawings stay unchanged. Global defaults live in Settings.</p></div></details>;
}
