import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {cellValue,filterLabel} from './tableModel.js';
import {useTableView} from './useTableView.js';
export function FilterEditor({column,values=[],rule,onChange,sort,onSort}) {
  const [search,setSearch]=useState('');const {key,label,kind='text'}=column;
  const options=[...new Set([...values,...(Array.isArray(rule)?rule:[])].map(String))].sort();
  return <div className="filter-editor"><strong>{label}</strong>{onSort&&<div className="ui-toolbar"><button onClick={()=>onSort({key,direction:'asc'})}>↑ {kind==='date'?'Oldest first':'Ascending'}</button><button onClick={()=>onSort({key,direction:'desc'})}>↓ {kind==='date'?'Newest first':'Descending'}</button></div>}
    {kind==='category'?<><input autoFocus aria-label={`Search ${label} values`} className="input" placeholder="Search values" value={search} onChange={e=>setSearch(e.target.value)}/><div className="ui-toolbar"><button onClick={()=>onChange(options)}>Select all</button><button onClick={()=>onChange([])}>Clear</button></div><div className="filter-options">{options.filter(v=>v.toLowerCase().includes(search.toLowerCase())).map(v=><label key={v}><input type="checkbox" checked={(rule||[]).includes(v)} onChange={()=>onChange((rule||[]).includes(v)?rule.filter(x=>x!==v):[...(rule||[]),v])}/>{v||'Unlabelled'}</label>)}</div></>:
    ['number','date'].includes(kind)?<>{kind==='number'&&<select aria-label={`${label} comparison`} className="input" value={rule?.operator||'between'} onChange={e=>onChange({...rule,kind,operator:e.target.value})}><option value="between">Between (inclusive)</option><option value="greater">Greater than</option><option value="less">Less than</option></select>}{[['min','From / minimum'],['max','To / maximum']].map(([bound,title])=><label key={bound}>{title}<input autoFocus={bound==='min'} aria-label={`${label} ${bound}`} type={kind==='date'?'date':'number'} className="input" value={rule?.[bound]??''} onChange={e=>onChange({...rule,kind,[bound]:e.target.value})}/></label>)}</>:
    <input autoFocus aria-label={`Search ${label}`} className="input" placeholder="Search" value={rule||''} onChange={e=>onChange(e.target.value)}/>}
    <button className="mini-btn" onClick={()=>onChange(null)}>Clear filter</button>
  </div>;
}
export default function DataTable(props) {
  return props.controller?<TableContents {...props}/>:<LocalTable {...props}/>;
}
function LocalTable(props) {
  const controller=useTableView(props.id,props.columns,props.rows,props.defaults);
  return <TableContents {...props} controller={controller}/>;
}
function TableContents({id,label='Data table',columns,rows,controller,defaults,manual=false,selected,onSelect,maxSelected=Infinity,actions,primaryAction,summary,onReset,toolbar,hideSearch=false,pageSize=20,expandedPageSize=100}) {
  const {view,setView,reset}=controller;const state=controller;
  const data=manual?rows:state.filtered;const [page,setPage]=useState(0),[popup,setPopup]=useState(null),[localSelected,setLocalSelected]=useState([]),[expanded,setExpanded]=useState(false);const focus=useRef(null);
  const selection=selected||localSelected,toggle=onSelect||((key)=>setLocalSelected(old=>old.includes(key)?old.filter(x=>x!==key):[...old,key]));
  const signature=JSON.stringify([view.filters,view.search,view.sort,rows.length]);useEffect(()=>setPage(0),[signature]);
  const close=()=>{setPopup(null);focus.current?.focus();};
  useEffect(()=>{const escape=e=>{if(e.key==='Escape')close();};document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape);},[]);
  const show=(key,event)=>{focus.current=event.currentTarget;const r=event.currentTarget.getBoundingClientRect();setPopup({key,left:Math.max(8,Math.min(r.left,window.innerWidth-320)),top:Math.min(r.bottom+4,window.innerHeight-350)});};
  const byKey=Object.fromEntries(columns.map(c=>[c.key,c]));const visible=view.order.filter(k=>view.columns.includes(k)).map(k=>byKey[k]).filter(Boolean);
  const updateFilter=(key,rule)=>setView(old=>({...old,filters:{...old.filters,[key]:rule}}));
  const effectivePageSize=expanded?Math.max(pageSize,expandedPageSize):pageSize;const count=Math.max(1,Math.ceil(data.length/effectivePageSize)),current=Math.min(page,count-1),shown=data.slice(current*effectivePageSize,(current+1)*effectivePageSize);
  return <section className="data-table" aria-label={label} data-density={view.density}>
    <div className="table-toolbar">{!hideSearch&&<input className="input table-search" aria-label={`Search ${label}`} placeholder="Search…" value={view.search} onChange={e=>setView({search:e.target.value})}/>}<button className="mini-btn" onClick={e=>show('columns',e)}>Columns</button><label className="sr-only" htmlFor={`${id}-density`}>Table density</label><select id={`${id}-density`} className="input table-density" value={view.density} onChange={e=>setView({density:e.target.value})}><option value="compact">Compact</option><option value="comfortable">Comfortable</option></select><button className="mini-btn" onClick={()=>{reset();setLocalSelected([]);onReset?.();}}>Reset view</button>{toolbar}{data.length>pageSize&&<button className="mini-btn" aria-pressed={expanded} onClick={()=>{setExpanded(v=>!v);setPage(0);}}>{expanded?`Show ${pageSize} rows`:`Expand to ${Math.max(pageSize,expandedPageSize)} rows`}</button>}<span className="table-count">N = {data.length}{selection.length?` · ${selection.length} selected`:''}</span></div>
    <div className="filter-chips">{Object.entries(view.filters).filter(([,r])=>r&&filterLabel(r)).map(([key,rule])=><button key={key} onClick={()=>updateFilter(key,null)} aria-label={`Remove ${byKey[key]?.label||key} filter`}>{byKey[key]?.label||key}: {filterLabel(rule)} ×</button>)}</div>
    {summary?.(data)}
    <div className="table-scroll" tabIndex="0" aria-label={`${label} scroll region`}><table><thead><tr><th className="selection-cell">Select</th>{visible.map((c,i)=><th key={c.key} className={i===0&&c.sticky?'sticky-key':''}><button aria-haspopup="dialog" aria-expanded={popup?.key===c.key} onClick={e=>show(c.key,e)}>{c.label} {view.sort.key===c.key?(view.sort.direction==='asc'?'↑':'↓'):'⌄'}{view.filters[c.key]&&filterLabel(view.filters[c.key])?' •':''}</button></th>)}{(actions||primaryAction)&&<th>Actions</th>}</tr></thead><tbody>{shown.map(row=><tr key={row.id} data-selected={selection.includes(row.id)}><td className="selection-cell"><input aria-label={`Select ${label} row ${row.id}`} type="checkbox" checked={selection.includes(row.id)} disabled={!selection.includes(row.id)&&selection.length>=maxSelected} onChange={()=>toggle(row.id)}/></td>{visible.map((c,i)=><td key={c.key} className={`${c.kind==='number'?'numeric':''} ${i===0&&c.sticky?'sticky-key':''} ${typeof c.cellClass==='function'?(c.cellClass(row)||''):c.cellClass||''}`.trim()}>{c.render?c.render(row):Array.isArray(cellValue(row,c))?cellValue(row,c).join(', '):cellValue(row,c)??'—'}</td>)}{(actions||primaryAction)&&<td><div className="row-actions">{primaryAction&&<button onClick={()=>primaryAction.onClick(row)}>{primaryAction.label||'Open'}</button>}{actions&&<button aria-label={`Actions for row ${row.id}`} aria-haspopup="dialog" onClick={e=>{show('actions',e);setPopup(old=>({...old,row}));}}>⋯</button>}</div></td>}</tr>)}</tbody></table>{!shown.length&&<p className="empty-state">No matching records. Clear filters or add a record.</p>}</div>
    {data.length>effectivePageSize&&<div className="table-toolbar"><button className="mini-btn" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>{current+1} / {count} · {effectivePageSize} rows/page</span><button className="mini-btn" disabled={current+1>=count} onClick={()=>setPage(current+1)}>Next</button></div>}
    {popup&&createPortal(<div className="table-overlay" onMouseDown={close}><div role="dialog" aria-label={popup.key==='columns'?'Table columns':popup.key==='actions'?'Row actions':`${byKey[popup.key]?.label} filter`} className="table-popover" style={{left:popup.left,top:Math.max(8,popup.top)}} onMouseDown={e=>e.stopPropagation()}><button className="popover-close" onClick={close} aria-label="Close table menu">×</button>{popup.key==='columns'?<div className="filter-editor"><strong>Visible columns and order</strong>{view.order.map((key,index)=><div key={key} className="column-choice"><label><input type="checkbox" checked={view.columns.includes(key)} disabled={view.columns.length===1&&view.columns.includes(key)} onChange={()=>setView({columns:view.columns.includes(key)?view.columns.filter(k=>k!==key):[...view.columns,key]})}/>{byKey[key]?.label}</label><button disabled={!index} aria-label={`Move ${byKey[key]?.label} left`} onClick={()=>{const order=[...view.order];[order[index-1],order[index]]=[order[index],order[index-1]];setView({order});}}>↑</button></div>)}</div>:popup.key==='actions'?<div className="filter-editor">{actions(popup.row).map(a=><button key={a.label} onClick={()=>{close();a.onClick();}}>{a.label}</button>)}</div>:<FilterEditor key={popup.key} column={byKey[popup.key]} values={byKey[popup.key].options||rows.flatMap(row=>{const v=cellValue(row,byKey[popup.key]);return Array.isArray(v)?v:[v??''];})} rule={view.filters[popup.key]} onChange={r=>updateFilter(popup.key,r)} sort={view.sort} onSort={sort=>setView({sort})}/>}</div></div>,document.body)}
  </section>;
}
