import DataTable from "../../components/table/DataTable.jsx";
import { useEffect, useState } from "react";
import { api } from "../../api/client";
import { DEFAULT_NAV } from "../../app/preferences";
import BrokerProfilesPanel from "../brokers/BrokerProfilesPanel";
import { TIMEZONE_OPTIONS } from "../../utils/timezones";

const accents = [["stone","Stone"],["blue","Blue"],["emerald","Emerald"],["violet","Violet"],["rose","Rose"],["amber","Amber"]];
export default function SettingsPage({ preferences, onChange }) {
  const [cache,setCache]=useState(null);
  const [status,setStatus]=useState(null); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [refreshing,setRefreshing]=useState(false);
  useEffect(()=>{ api.cacheDiagnostics().then(setCache).catch(e=>setError(e.message)); api.dataStatus().then(setStatus).catch(e=>setError(e.message)); },[]);
  const set=(patch)=>onChange({ ...preferences, ...patch });
  const move=(index,delta)=>{ const list=[...(preferences.navOrder||DEFAULT_NAV)]; const j=index+delta; if(j<0||j>=list.length)return; [list[index],list[j]]=[list[j],list[index]]; set({navOrder:list}); };
  const refresh=async()=>{ setRefreshing(true); setError(""); setMessage(""); try{ const r=await api.refreshSymbols(); setMessage(`Loaded ${Number(r.symbols||0).toLocaleString()} symbols from ${r.source}.`); setStatus(await api.dataStatus()); } catch(e){setError(e.message)} finally{setRefreshing(false)} };
  return <div className="max-w-5xl">
    <p className="text-xs uppercase tracking-widest text-stone-500">Ledger</p><h2 className="mt-1 text-3xl font-semibold">Settings</h2><p className="mt-2 text-sm text-stone-600">Appearance, chart defaults, navigation and local data maintenance.</p>
    {error&&<div className="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message&&<div className="mt-4 rounded border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}
    <p className="muted text-xs mt-3">Charts powered by <a href="https://www.tradingview.com/" target="_blank" rel="noreferrer" className="underline">TradingView Lightweight Charts</a> (TradingView, Inc.; Apache-2.0).</p>
    <Section title="Appearance"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      <Field label="Theme"><select className="input" value={preferences.theme} onChange={e=>set({theme:e.target.value})}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></Field>
      <Field label="Accent"><select className="input" value={preferences.accent} onChange={e=>set({accent:e.target.value})}>{accents.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
      <Field label="Density"><select className="input" value={preferences.density} onChange={e=>set({density:e.target.value})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></Field>

    </div></Section>
    <Section title="Chart defaults"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      <Field label="Default timezone"><select className="input" value={preferences.timeZone} onChange={e=>set({timeZone:e.target.value})}>{TIMEZONE_OPTIONS.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></Field>
      <Field label="Default session"><select className="input" value={preferences.chartSession} onChange={e=>set({chartSession:e.target.value})}><option value="regular">Regular</option><option value="extended">Extended</option></select></Field>
      <Field label="Default timeframe"><select className="input" value={preferences.chartTimeframe||"5m"} onChange={e=>set({chartTimeframe:e.target.value})}>{["1m","5m","15m","30m","1h","4h","1d"].map(x=><option key={x}>{x}</option>)}</select></Field>
      {[["chartGridVisible","Show grid"],["chartVolumeVisible","Show volume"],["chartCrosshair","Show crosshair"],["chartAutoScale","Auto scale"]].map(([key,label])=><label key={key}><input type="checkbox" checked={preferences[key]!==false} onChange={e=>set({[key]:e.target.checked})}/> {label}</label>)}<Field label="Initial visible bars"><input className="input" type="number" min="60" max="2000" value={preferences.chartVisibleBars||180} onChange={e=>set({chartVisibleBars:Math.max(60,Math.min(2000,Number(e.target.value)||180))})}/></Field>
      <ColorField label="Up candle" value={preferences.chartUp} onChange={v=>set({chartUp:v})}/><ColorField label="Down candle" value={preferences.chartDown} onChange={v=>set({chartDown:v})}/><ColorField label="Chart background" value={preferences.chartBackground} onChange={v=>set({chartBackground:v})}/><ColorField label="Grid" value={preferences.chartGrid} onChange={v=>set({chartGrid:v})}/>
    </div></Section>
    <Section title="Replay defaults"><div className="ui-toolbar"><Field label="Context"><select className="input" value={preferences.replayContext||"5d"} onChange={e=>set({replayContext:e.target.value})}>{['1d','5d','1m','3m'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Playback speed"><select className="input" value={preferences.replaySpeed||1} onChange={e=>set({replaySpeed:Number(e.target.value)})}>{[.5,1,2,5,10].map(n=><option key={n} value={n}>{n}x</option>)}</select></Field><label><input type="checkbox" checked={Boolean(preferences.replayFollow)} onChange={e=>set({replayFollow:e.target.checked})}/> Follow replay</label>{[["replayAutoJournal","Auto-journal closed trades"],["replayConfirm","Confirm replay orders"],["replayHelp","Show shortcut help"]].map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(preferences[key])} onChange={e=>set({[key]:e.target.checked})}/> {label}</label>)}</div><p className="muted text-xs mt-3">Auto-journal defaults to on. When off, use Save closed trade to Journal before starting another. Order shortcuts focus the ticket before submission; rewind remains review mode.</p></Section>
    <Section title="Backtest defaults"><div className="ui-toolbar mb-3"><Field label="Sizing mode"><select className="input" value={preferences.backtestSizing} onChange={e=>set({backtestSizing:e.target.value})}><option value="risk_pct">Risk %</option><option value="quantity">Fixed quantity</option><option value="cash_position">Fixed notional</option></select></Field><Field label="Default session"><select className="input" value={preferences.backtestSession} onChange={e=>set({backtestSession:e.target.value})}>{["auto","regular","extended","24h"].map(x=><option key={x}>{x}</option>)}</select></Field></div><div className="grid gap-4 sm:grid-cols-3">{[['backtestCapital','Starting balance',10000],['backtestRisk','Risk / size value',1],['backtestCommission','Commission per order',0]].map(([key,label,fallback])=><Field key={key} label={label}><input className="input" type="number" min={key==='backtestCapital'?1:0} step="any" value={preferences[key]??fallback} onChange={e=>set({[key]:Number(e.target.value)})}/></Field>)}</div><p className="muted text-xs mt-3">Applied to new configurations. Saved-run settings retain their original costs and account assumptions. Validation splits remain chronological.</p></Section>
    <Section title="Journal"><p className="muted text-sm">Journal uses the timezone above. Filters, columns and density persist per view; Reset view restores presentation without changing trades, notes or attachments.</p></Section>
    <Section title="Drawing defaults"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Magnet / snap"><select className="input" value={preferences.drawingMagnet||"weak"} onChange={e=>set({drawingMagnet:e.target.value})}><option value="off">Off</option><option value="weak">Weak</option><option value="strong">Strong</option></select></Field><ColorField label="Default drawing colour" value={preferences.drawingColor||"#60a5fa"} onChange={v=>set({drawingColor:v})}/></div><p className="mt-3 text-xs text-stone-500">Drawings are stored in timestamp/price coordinates so they remain attached to market structure as you zoom, resize or switch timeframe.</p></Section>
    <Section title="Top navigation order"><p className="mb-3 text-xs text-stone-500">Reorder the main app areas without changing their underlying routes.</p><div className="space-y-2">{(preferences.navOrder||DEFAULT_NAV).map((item,i)=><div key={item} className="flex items-center justify-between rounded-lg border border-stone-200 bg-white px-4 py-3"><span className="font-medium">{({Dashboard:"Overview",Screener:"Research","Investment Portfolio":"Portfolio"})[item]||item}</span><div className="flex gap-2"><button className="mini-btn" disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button className="mini-btn" disabled={i===(preferences.navOrder||DEFAULT_NAV).length-1} onClick={()=>move(i,1)}>↓</button></div></div>)}</div><button className="mt-3 mini-btn" onClick={()=>set({navOrder:DEFAULT_NAV})}>Reset order</button></Section>
    <Section title="Data cache">{cache&&<><p className="muted text-xs mb-3">{cache.note}</p><DataTable id="cache-diagnostics" label="Cached history" rows={cache.items.map((r,i)=>({...r,id:i}))} columns={[...["ticker","source_timeframe","provider_cache"].map(key=>({key,label:key.replaceAll("_"," "),kind:"text"})),...["covered_start","covered_end","updated_at"].map(key=>({key,label:key.replaceAll("_"," "),kind:"date"}))]}/></>}<button className="mini-btn" onClick={()=>{api.clearChartCache();setMessage("Frontend chart cache cleared. Market history and trading data are unchanged.");}}>Clear frontend chart cache</button><p className="muted text-xs mt-2">Use Refresh on a chart to bypass the request cache. Historical provider caches remain available for reproducible runs.</p></Section>
    <BrokerProfilesPanel/><Section title="Data & providers"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Symbols" value={status?.symbols_cached}/><Stat label="Fundamentals" value={status?.screener_coverage?.fundamentals}/><Stat label="Prices" value={status?.screener_coverage?.prices}/><Stat label="Providers" value={status?Object.values(status.providers||{}).filter(x=>x.configured).length:"—"}/></div>{status?.providers&&<div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(status.providers).map(([key,item])=><div key={key} className="rounded-lg border border-stone-200 bg-stone-50 p-3"><div className="flex items-center justify-between gap-2"><strong className="text-sm uppercase">{key}</strong><span className={`text-xs font-medium ${item.configured?"text-emerald-700":"text-stone-400"}`}>{item.configured?"Configured":"Not configured"}</span></div><p className="mt-1 text-xs text-stone-500">{item.purpose}</p>{key==="oanda"&&<p className="mt-2 text-xs text-stone-600">Candles: {item.configured?"configured":"not configured"} &middot; Journal history: {item.journal_configured?"configured (read only)":"not configured"}. Journal history requires both token and account ID.</p>}</div>)}</div>}<button className="mt-4 ledger-primary rounded-md px-4 py-2 text-sm text-white" onClick={refresh} disabled={refreshing}>{refreshing?"Refreshing…":"Refresh symbol universe"}</button><p className="mt-2 text-xs text-stone-500">Symbol refresh remains the US-equity security master; XAUUSD and NQ1! are provider-routed aliases and do not need to be inserted into that table.</p></Section>
  </div>;
}
function Section({title,children}){return <section className="mt-6 rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-semibold">{title}</h3><div className="mt-4">{children}</div></section>}
function Field({label,children}){return <label className="block"><span className="mb-1 block text-xs font-medium text-stone-500">{label}</span>{children}</label>}
function ColorField({label,value,onChange}){return <Field label={label}><div className="flex gap-2"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-14 rounded border border-stone-300 bg-white"/><input className="input" value={value} onChange={e=>onChange(e.target.value)}/></div></Field>}
function Stat({label,value}){const shown=value==null||value==="—"?"—":Number.isFinite(Number(value))?Number(value).toLocaleString():String(value);return <div className="rounded-lg bg-stone-50 p-4"><p className="text-xs text-stone-500">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums">{shown}</p></div>}
