import { useEffect, useState } from 'react';
import { api } from '../../api/client';
import { Summary } from './JournalShared';
import { rValue, sourceLabel, pnlSummary } from './journalUtils';
export default function AnalysisView({filters,revision,playbooks}) {
  const [report,setReport]=useState(null),[group,setGroup]=useState('playbook'),[loading,setLoading]=useState(true),[error,setError]=useState('');const query=JSON.stringify(filters);
  useEffect(()=>{let active=true;setLoading(true);setError('');api.journalReport(JSON.parse(query)).then(r=>{if(active)setReport(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query,revision]);
  const label=k=>{if(!k.startsWith('playbook_field:'))return k.replaceAll('_',' ');const [bookId,...fieldId]=k.slice(15).split(':');const book=playbooks.find(p=>p.id===Number(bookId));const field=book?.review_fields.find(f=>f.id===fieldId.join(':'));return `${book?.title||'Earlier Playbook'} / ${field?.label||report?.trades.find(t=>t.review_data?.custom_labels?.[k.slice(15)])?.review_data.custom_labels[k.slice(15)]||fieldId.join(':')}`;};
  const exportCsv=()=>{const cols=['opened_at','closed_at','journal_date','ticker','direction','source','account','account_currency','position_currency','playbook_title','setup','setup_grade','plan_followed','entry_price','stop_loss','take_profit','exit_price','quantity','planned_rr','r_multiple','pnl_amount','broker_realized_pnl','pnl_source','costs_complete'];const esc=v=>{let s=String(v??'');if(/^[=+@\t\r]/.test(s)||(/^-.+/.test(s)&&!Number.isFinite(Number(s))))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const csv=[cols.join(','),...(report?.trades||[]).map(t=>cols.map(c=>esc(t[c])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='ledger-journal-filtered.csv';a.click();URL.revokeObjectURL(a.href);};
  const rows=report?.breakdowns?.[group]||[];
  return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><h3 className="text-xl font-semibold">Journal analysis</h3><button className="mini-btn" disabled={loading||!report?.trades.length} onClick={exportCsv}>Export filtered CSV</button></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{loading?<p className="p-8 text-center text-stone-500">Analysing trades...</p>:report&&<><Summary data={report.summary}/><label className="block text-sm">Compare by <select className="input ml-2 inline-block w-72 capitalize" value={group} onChange={e=>setGroup(e.target.value)}>{Object.keys(report.breakdowns).map(k=><option key={k} value={k}>{label(k)}</option>)}</select></label><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-stone-50"><tr>{['Group','N','Win rate','R count','Average R','Total R','PF (R)','P&L by currency'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r[group]}><td className="p-3 font-medium">{group==='source'?sourceLabel(r[group]):r[group]}</td><td className="p-3 font-semibold">{r.trades}</td><td className="p-3">{r.win_rate==null?'—':`${r.win_rate.toFixed(1)}%`}</td><td className="p-3">{r.r_trades}</td><td className="p-3">{rValue(r.average_r)}</td><td className="p-3">{rValue(r.total_r)}</td><td className="p-3">{r.profit_factor_r==='inf'?'Infinity':r.profit_factor_r==null?'—':Number(r.profit_factor_r).toFixed(2)}</td><td className="p-3">{pnlSummary(r)}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-stone-500">No trades match these filters.</p>}</div><p className="text-xs text-stone-500">A trade can appear under multiple mistake, emotion or multi-choice tags. Those buckets are not additive. Compare sample sizes before drawing conclusions.</p></>}</div>;
}
