import {useMemo,useState} from 'react';
import {useUIPreference} from '../../app/useUIPreference.js';
import {Summary} from './JournalShared';
import {rValue,sourceLabel,pnlSummary} from './journalUtils';
import {MetricBars,SeriesChart} from '../../components/insights/MetricCharts.jsx';
import {analysisDimensions,compositeBreakdown,sortBreakdown} from './analysisBreakdown.js';
const weekdays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const metrics=[['average_r','Expectancy'],['win_rate','Win rate'],['total_r','Total R'],['trades','N'],['profit_factor_r','Profit factor']];
function Heatmap({rows}) {
  const [metric,setMetric]=useUIPreference('journal.heatmapMetric','average_r');
  const times=[...new Set(rows.map(r=>r.weekday_time?.split(' ')[1]).filter(v=>v&&v!=='Unknown'))].sort();const index=Object.fromEntries(rows.map(r=>[r.weekday_time,r]));
  return <section className="insight-panel"><div className="ui-toolbar"><h4>Weekday × entry time</h4><label>Cell metric <select className="input table-density" value={metric} onChange={e=>setMetric(e.target.value)}>{metrics.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label></div><p className="muted text-xs mt-2">30-minute buckets · Journal timezone · N shown in every measured cell. Low sample: N &lt; 20.</p><div className="table-scroll mt-3"><table className="heatmap"><thead><tr><th>Day</th>{times.map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{weekdays.map(day=><tr key={day}><th>{day}</th>{times.map(time=>{const r=index[day+' '+time],v=r?.[metric];return <td key={time} className={r&&typeof v==='number'?(['average_r','total_r'].includes(metric)?(v>0?'heat-positive':v<0?'heat-negative':''):'heat-info'):''} title={r?`${day} ${time}; N=${r.trades}; ${r.trades<20?'Low sample':'Descriptive only'}`:'No observations'}><strong>{v==='inf'?'No losses':typeof v==='number'?v.toFixed(metric==='trades'?0:2):'—'}</strong>{r&&<small>N={r.trades}{r.trades<20?' · Low sample':''}</small>}</td>;})}</tr>)}</tbody></table></div></section>;
}
function customLabel(key,playbooks,report) {
  if(!key.startsWith('playbook_field:'))return key.replaceAll('_',' ');
  const raw=key.slice('playbook_field:'.length),[bookId,...fieldId]=raw.split(':');
  const book=playbooks.find(p=>p.id===Number(bookId));
  const stored=(report?.trades||[]).find(t=>t.review_data?.custom_labels?.[raw])?.review_data.custom_labels[raw];
  return `${book?.title||'Earlier Playbook'} / ${book?.review_fields?.find(f=>f.id===fieldId.join(':'))?.label||stored||fieldId.join(':')}`;
}
export default function AnalysisView({report,loading,error,playbooks=[]}) {
  const [storedDimensions,setStoredDimensions]=useUIPreference('journal.analysisGroups',['playbook']);
  const dimensions=Array.isArray(storedDimensions)&&storedDimensions.length?storedDimensions.slice(0,4):['playbook'];
  const [detailSort,setDetailSort]=useUIPreference('journal.analysisDetailSort','sample');
  const [showAllBreakdown,setShowAllBreakdown]=useState(false);
  const exportCsv=()=>{const cols=['opened_at','closed_at','journal_date','ticker','direction','source','account','account_currency','position_currency','playbook_title','setup','setup_grade','plan_followed','entry_price','stop_loss','take_profit','exit_price','quantity','planned_rr','r_multiple','pnl_amount','broker_realized_pnl','pnl_source','costs_complete'];const esc=v=>{let s=String(v??'');if(/^[=+@\t\r]/.test(s)||(/^-.+/.test(s)&&!Number.isFinite(Number(s))))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const csv=[cols.join(','),...(report?.trades||[]).map(t=>cols.map(c=>esc(t[c])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='ledger-journal-filtered.csv';a.click();URL.revokeObjectURL(a.href);};
  const groups=report?.breakdowns||{};
  const customDimensions=Object.keys(groups).filter(k=>k.startsWith('playbook_field:')).map(k=>[k,customLabel(k,playbooks,report)]);
  const availableDimensions=[...analysisDimensions,...customDimensions];
  const detailRows=useMemo(()=>sortBreakdown(compositeBreakdown(report?.trades||[],dimensions,report?.timezone),detailSort),[report?.trades,report?.timezone,dimensions.join('|'),detailSort]);
  const visibleRows=showAllBreakdown?detailRows:detailRows.slice(0,20);
  const labelFor=key=>availableDimensions.find(([k])=>k===key)?.[1]||customLabel(key,playbooks,report);
  const toggleDimension=key=>{const has=dimensions.includes(key);const next=has?dimensions.filter(k=>k!==key):dimensions.length<4?[...dimensions,key]:dimensions;setStoredDimensions(next.length?next:['playbook']);setShowAllBreakdown(false);};
  return <div className="space-y-5"><div className="ui-toolbar"><h3 className="text-xl font-semibold">Journal analysis</h3><button className="mini-btn" disabled={loading||!report?.trades.length} onClick={exportCsv}>Export filtered CSV</button></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{loading?<p className="empty-state">Analysing trades…</p>:report&&<><Summary data={report.summary}/><p className="muted text-sm">Patterns below describe this filtered sample. They do not establish a causal edge or a trading rule.</p><div className="insight-grid"><SeriesChart title="Cumulative R" points={report.r_curve||[]} valueKey="cumulative_r" description="Closed trades with recorded R."/><SeriesChart title="R drawdown" points={report.r_curve||[]} valueKey="drawdown_r" description="Decline from the prior cumulative-R peak."/><SeriesChart title="Rolling expectancy" points={report.r_curve||[]} valueKey="rolling_expectancy" description="Last 20 recorded-R trades; earlier windows are low sample."/><MetricBars title="Expectancy by entry hour" rows={groups.entry_hour||[]} labelKey="entry_hour"/></div><Heatmap rows={groups.weekday_time||[]}/><div className="insight-grid">{[['weekday','Weekday'],['session','Session'],['playbook','Strategy / Playbook'],['setup','Setup'],['direction','Long vs short'],['month','Month'],['entry_10min','10-minute entry buckets'],['entry_30min','30-minute entry buckets'],['plan_followed','Plan adherence'],['setup_grade','Grade'],['mistake','Mistakes'],['confluence','Confluences'],['market_condition','Market regime']].map(([key,title])=><MetricBars key={key} title={title} rows={groups[key]||[]} labelKey={key}/>)}</div>
    <section className="insight-panel"><div className="analysis-breakdown-controls"><div><h4>Detailed multi-factor breakdown</h4><p className="muted text-xs mt-1">Combine up to four dimensions to inspect interactions such as strategy + session + time + emotion.</p></div><label className="text-xs">Sort rows<select className="input table-density mt-1" value={detailSort} onChange={e=>{setDetailSort(e.target.value);setShowAllBreakdown(false);}}><option value="sample">Largest sample</option><option value="best">Best average R</option><option value="worst">Worst average R</option><option value="win_rate">Highest win rate</option><option value="total_r">Highest total R</option><option value="label">Label</option></select></label></div><div className="analysis-breakdown-dimensions">{dimensions.map(key=><span key={key}>{labelFor(key)}</span>)}</div><details className="mt-3"><summary className="cursor-pointer text-xs font-medium">Choose dimensions ({dimensions.length}/4)</summary><div className="analysis-dimension-picker">{availableDimensions.map(([key,label])=><label key={key}><input type="checkbox" checked={dimensions.includes(key)} disabled={!dimensions.includes(key)&&dimensions.length>=4} onChange={()=>toggleDimension(key)}/><span>{label}</span></label>)}</div></details>
      <div className="table-scroll mt-4"><table className="comparison-grid text-sm"><thead><tr>{dimensions.map(key=><th key={key}>{labelFor(key)}</th>)}{['N','Win rate','R count','Average R','Total R','PF (R)','P&L by currency'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visibleRows.map(row=><tr key={row.id}>{dimensions.map(key=><td key={key}>{key==='source'?sourceLabel(row.values[key]):row.values[key]}</td>)}<td>{row.trades}{row.trades<20?' · Low sample':''}</td><td>{row.win_rate==null?'—':`${row.win_rate.toFixed(1)}%`}</td><td>{row.r_trades}</td><td>{rValue(row.average_r)}</td><td>{rValue(row.total_r)}</td><td>{row.profit_factor_r==='inf'?'No losses':row.profit_factor_r==null?'—':Number(row.profit_factor_r).toFixed(2)}</td><td>{pnlSummary(row)}</td></tr>)}</tbody></table>{!visibleRows.length&&<p className="empty-state">No combinations for the selected dimensions.</p>}</div>{detailRows.length>20&&<button className="mini-btn mt-3" onClick={()=>setShowAllBreakdown(v=>!v)}>{showAllBreakdown?'Show 20':`Expand all ${detailRows.length}`}</button>}<p className="muted text-xs mt-3">Multi-choice dimensions can place the same trade in more than one combination; grouped rows are descriptive and are not additive.</p></section></>}</div>;
}
