import { useEffect, useMemo, useState } from "react";
import { api } from "../../api/client";
const groups=[["symbol","Symbol"],["setup","Setup"],["entry_hour","Entry hour"],["weekday","Weekday"],["timeframe","Timeframe"],["direction","Long / short"],["market_condition","Market condition"],["source","Source"]];
const blank={source:"",ticker:"",direction:"",result:"",setup:"",entry_timeframe:"",market_condition:"",date_from:"",date_to:""};
export default function AnalysisView(){
 const [filters,setFilters]=useState(blank); const [report,setReport]=useState(null); const [group,setGroup]=useState("symbol"); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const run=async(next=filters)=>{setLoading(true);setError("");try{setReport(await api.journalReport(next))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{void run(blank)},[]);
 const rows=report?.breakdowns?.[group]||[]; const s=report?.summary||{}; const options=useMemo(()=>{const t=report?.trades||[]; const uniq=k=>[...new Set(t.map(x=>x[k]).filter(Boolean))].sort(); return {setups:uniq("setup"),timeframes:uniq("entry_timeframe"),markets:uniq("market_condition")}},[report]);
 const reset=()=>{setFilters(blank);void run(blank)};
 const exportCsv=()=>{const t=report?.trades||[]; if(!t.length)return; const cols=["opened_at","closed_at","ticker","direction","source","setup","entry_timeframe","entry_price","stop_loss","take_profit","exit_price","planned_rr","r_multiple","pnl_amount","pnl_pct","market_condition"]; const esc=v=>`"${String(v??"").replaceAll('"','""')}"`; const csv=[cols.join(","),...t.map(x=>cols.map(c=>esc(x[c])).join(","))].join("\n"); const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="ledger-journal-filtered.csv";a.click();URL.revokeObjectURL(a.href)};
 return <div>
  <div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-xl font-semibold">Journal analysis</h3><p className="mt-1 max-w-3xl text-sm text-stone-600">Tradervue-style drill-downs across your own trades. Filter first, then compare where your execution actually performs best/worst.</p></div><button className="mini-btn" onClick={exportCsv}>Export filtered CSV</button></div>
  <section className="mt-4 rounded-xl border border-stone-200 bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Field label="Ticker contains"><input className="input" value={filters.ticker} onChange={e=>setFilters({...filters,ticker:e.target.value})}/></Field><Field label="Source"><select className="input" value={filters.source} onChange={e=>setFilters({...filters,source:e.target.value})}><option value="">All</option><option value="live_manual">Live manual</option><option value="paper_manual">Paper manual</option><option value="replay">Replay</option><option value="backtest">Backtest</option></select></Field><Field label="Direction"><select className="input" value={filters.direction} onChange={e=>setFilters({...filters,direction:e.target.value})}><option value="">All</option><option value="long">Long</option><option value="short">Short</option></select></Field><Field label="Result"><select className="input" value={filters.result} onChange={e=>setFilters({...filters,result:e.target.value})}><option value="">All</option><option value="win">Win</option><option value="loss">Loss</option><option value="breakeven">B/E</option></select></Field><Field label="Setup"><select className="input" value={filters.setup} onChange={e=>setFilters({...filters,setup:e.target.value})}><option value="">All</option>{options.setups.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Entry timeframe"><select className="input" value={filters.entry_timeframe} onChange={e=>setFilters({...filters,entry_timeframe:e.target.value})}><option value="">All</option>{options.timeframes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Market condition"><select className="input" value={filters.market_condition} onChange={e=>setFilters({...filters,market_condition:e.target.value})}><option value="">All</option>{options.markets.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="From"><input type="date" className="input" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})}/></Field><Field label="To"><input type="date" className="input" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})}/></Field><div className="flex items-end gap-2"><button className="ledger-primary rounded-md px-4 py-2 text-sm text-white" onClick={()=>run()} disabled={loading}>{loading?"Analysing…":"Apply filters"}</button><button className="mini-btn h-10" onClick={reset}>Reset</button></div></div></section>
  {error&&<div className="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Trades" value={s.trades??0}/><Stat label="Win rate" value={s.win_rate==null?"—":`${s.win_rate.toFixed(1)}%`}/><Stat label="Average R" value={s.average_r==null?"—":`${signed(s.average_r)}R`}/><Stat label="Total R" value={s.total_r==null?"—":`${signed(s.total_r)}R`}/><Stat label="Avg duration" value={s.average_duration_min==null?"—":`${Math.round(s.average_duration_min)} min`}/></div>
  <section className="mt-5 rounded-xl border border-stone-200 bg-white shadow-sm"><div className="border-b border-stone-200 p-4"><div className="flex flex-wrap gap-2">{groups.map(([k,l])=><button key={k} onClick={()=>setGroup(k)} className={`mini-btn ${group===k?"active-btn":""}`}>{l}</button>)}</div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="px-4 py-3 text-left">{groups.find(x=>x[0]===group)?.[1]}</th><th className="px-4 py-3 text-right">Trades</th><th className="px-4 py-3 text-right">Win rate</th><th className="px-4 py-3 text-right">Avg R</th><th className="px-4 py-3 text-right">Total R</th><th className="px-4 py-3 text-right">PF (R)</th></tr></thead><tbody className="divide-y divide-stone-100">{rows.map((x,i)=>{const key=x[group];return <tr key={`${key}-${i}`}><td className="px-4 py-3 font-medium">{String(key)}</td><td className="px-4 py-3 text-right">{x.trades}</td><td className="px-4 py-3 text-right">{x.win_rate==null?"—":`${x.win_rate.toFixed(1)}%`}</td><td className={`px-4 py-3 text-right ${tone(x.average_r)}`}>{x.average_r==null?"—":`${signed(x.average_r)}R`}</td><td className={`px-4 py-3 text-right ${tone(x.total_r)}`}>{x.total_r==null?"—":`${signed(x.total_r)}R`}</td><td className="px-4 py-3 text-right">{x.profit_factor_r==null?"—":x.profit_factor_r>=999?"∞":Number(x.profit_factor_r).toFixed(2)}</td></tr>})}</tbody></table>{!rows.length&&<p className="p-8 text-center text-sm text-stone-500">No trades match these filters.</p>}</div></section>
  <p className="mt-4 text-xs text-stone-500">Use these breakdowns to generate hypotheses, not to delete every losing bucket. A pattern should survive enough trades and ideally a later untouched sample before you treat it as an edge.</p>
 </div>
}
function Field({label,children}){return <label><span className="mb-1 block text-xs font-medium text-stone-500">{label}</span>{children}</label>}
function Stat({label,value}){return <div className="rounded-xl border border-stone-200 bg-white p-4 shadow-sm"><p className="text-xs uppercase text-stone-500">{label}</p><p className="mt-2 text-xl font-semibold tabular-nums">{value}</p></div>}
function signed(v){const n=Number(v);return `${n>=0?"+":""}${n.toFixed(2)}`}
function tone(v){return Number(v)>0?"text-emerald-700":Number(v)<0?"text-red-700":""}
