import { useEffect, useState } from 'react';
import { api } from '../../api/client';
import { journalToday, pnlSummary, rValue } from './journalUtils';
export default function CalendarView({filters,timeZone,revision,onOpenDay}) {
  const [month,setMonth]=useState(()=>journalToday(timeZone).slice(0,7)),[days,setDays]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const query=JSON.stringify(filters);
  useEffect(()=>{if(!month)return;let active=true;setLoading(true);setError('');api.journalCalendar(month,JSON.parse(query)).then(r=>{if(active)setDays(r.days||[]);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[month,query,revision]);
  const [year,mon]=month.split('-').map(Number),first=new Date(Date.UTC(year,mon-1,1));
  const cells=month?Array.from({length:42},(_,i)=>new Date(Date.UTC(year,mon-1,1-first.getUTCDay()+i))):[];
  const map=Object.fromEntries(days.map(d=>[d.day,d]));
  return <div className="space-y-4"><label className="text-sm">Month <input aria-label="Calendar month" type="month" className="input ml-2 inline-block w-44" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setSelected(null);}}}/></label><p className="text-xs text-stone-500">Each day groups trades by entry time in {timeZone}. Select a day for trades or a Daily Review; Daily Review includes all trades for its selected account.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{loading?<p className="p-8 text-center text-stone-500">Loading calendar...</p>:<div className="overflow-x-auto rounded-xl border bg-white"><div className="grid min-w-[650px] grid-cols-7">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div key={d} className="bg-stone-50 p-3 text-xs text-stone-500">{d}</div>)}{cells.map(date=>{const key=date.toISOString().slice(0,10),day=map[key],inMonth=key.startsWith(month);return <button key={key} aria-label={`${key}, ${day?.trades||0} trades`} onClick={()=>setSelected(key)} className={`min-h-28 border-b border-r p-2 text-left ${selected===key?'bg-blue-50':inMonth?'':'bg-stone-50 text-stone-400'}`}><p className="text-right text-xs">{date.getUTCDate()}</p>{day&&<div className="mt-2 space-y-1 text-xs"><p className="font-semibold">{day.trades} trades</p><p>{day.wins}W / {day.losses}L / {day.breakevens} BE</p><p>{rValue(day.total_r)}</p><p className="break-words">{pnlSummary(day)}</p></div>}</button>;})}</div></div>}{selected&&<div className="flex flex-wrap items-center gap-3 rounded-lg border bg-white p-4"><strong className="text-sm">{selected}</strong><button className="mini-btn" onClick={()=>onOpenDay(selected,'Trades')}>View day trades</button><button className="mini-btn" onClick={()=>onOpenDay(selected,'Daily Review')}>Open Daily Review</button></div>}</div>;
}
