import {useMemo,useState} from 'react';
import {journalToday,pnlSummary,rValue,moneyCurrency} from './journalUtils';
import {useUIPreference} from '../../app/useUIPreference.js';
import {calendarDays,calendarTone,weeklySummary} from './calendarModel.js';
export default function CalendarView({timeZone,onOpenDay,report,loading,error}) {
  const [month,setMonth]=useUIPreference('journal.calendarMonth',journalToday(timeZone).slice(0,7)),[selected,setSelected]=useState(null);
  const days=useMemo(()=>calendarDays(report?.trades||[],month),[report?.trades,month]);
  const [year,mon]=month.split('-').map(Number),first=new Date(Date.UTC(year,mon-1,1)),map=Object.fromEntries(days.map(d=>[d.day,d]));
  const cells=Array.from({length:42},(_,i)=>new Date(Date.UTC(year,mon-1,1-first.getUTCDay()+i)).toISOString().slice(0,10));
  const trades=(report?.trades||[]).filter(t=>t.journal_date===selected);
  return <div className="space-y-4"><div className="ui-toolbar"><label>Month <input aria-label="Calendar month" type="month" className="input table-density" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setSelected(null);}}}/></label><span className="muted text-xs">Entry dates in {timeZone} · Click a day to review its trades.</span></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{loading&&!report?<p className="empty-state">Loading calendar…</p>:<div className="calendar-scroll"><div className="calendar-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat','Week'].map(d=><div className="calendar-heading" key={d}>{d}</div>)}{Array.from({length:6},(_,week)=>{const keys=cells.slice(week*7,week*7+7),weekly=weeklySummary(keys.map(k=>map[k]).filter(Boolean));return [...keys.map(key=>{const day=map[key];return <button key={key} aria-label={`${key}, ${day?.trades||0} trades`} aria-pressed={selected===key} onClick={()=>setSelected(key)} className={`calendar-day day-${calendarTone(day)} ${key.startsWith(month)?'':'outside-month'}`}><span className="calendar-date">{Number(key.slice(-2))}</span>{day?<><strong>{pnlSummary(day)}</strong><span>{rValue(day.total_r)}</span><small>N = {day.trades} trades</small></>:<small>{key.startsWith(month)?'No trades':'Outside month'}</small>}</button>;}),<div className="calendar-week" key={`week-${week}`}><small>Week (selected month)</small><strong>{pnlSummary(weekly)}</strong><span>{rValue(weekly.total_r)}</span><small>{weekly.trades} trades · {weekly.win_rate==null?'—':`${weekly.win_rate.toFixed(0)}% wins`}</small></div>];})}</div></div>}
    {selected&&<section className="insight-panel" aria-label="Selected calendar day"><div className="ui-toolbar"><h4>{selected}</h4><span>{pnlSummary(map[selected])} · {rValue(map[selected]?.total_r)} · N = {trades.length}</span><button className="mini-btn" onClick={()=>onOpenDay(selected,'Daily Review')}>Open Daily Review</button><button className="mini-btn" onClick={()=>onOpenDay(selected,'Trades')}>View day trades</button><button className="mini-btn" onClick={()=>setSelected(null)}>Close day</button></div><div className="calendar-day-trades">{trades.map(t=><div key={t.id}><strong>{t.ticker}</strong><span>{t.direction}</span><span>{rValue(t.r_multiple)}</span><span>{moneyCurrency(t.pnl_amount,t.account_currency||t.position_currency||'USD')}</span></div>)}</div>{!trades.length&&<p className="muted text-sm mt-3">No matching trades on this day.</p>}</section>}
  </div>;
}
