import { useEffect, useState } from 'react';
import { api } from '../../api/client';
import { Choice, TextNote } from './ReviewFields';
import { Summary, Attachments, useUnsaved } from './JournalShared';
import { journalToday } from './journalUtils';
export default function DailyReviewView({initialDay,timeZone,options,onDirtyChange}) {
  const [key,setKey]=useState(()=>({date:initialDay?.date||journalToday(timeZone),account:initialDay?.account||'Main'}));
  const [picker,setPicker]=useState(key),[form,setForm]=useState(null),[baseline,setBaseline]=useState(null),[summary,setSummary]=useState({}),[recent,setRecent]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  const dirty=JSON.stringify(form)!==JSON.stringify(baseline);useUnsaved(dirty,onDirtyChange);
  useEffect(()=>{let active=true;setLoading(true);setError('');setMessage('');setForm(null);setBaseline(null);Promise.all([api.dailySummary(key.date,key.account,timeZone),api.dailyReviews()]).then(([r,list])=>{if(active){const next=r.review||{review_date:key.date,account:key.account};setForm(next);setBaseline(next);setSummary(r.summary);setRecent(list.items||[]);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[key,timeZone]);
  const choose=next=>{if(!next.date||!next.account.trim()){setError('Choose a date and account.');return;}if(!dirty||confirm('Discard unsaved Daily Review changes?')){setPicker(next);setKey({...next,account:next.account.trim()});}};
  const save=async e=>{e.preventDefault();setSaving(true);setError('');try{const saved=await api.saveDailyReview(form);const next={...saved,attachments:form.attachments||[]};setForm(next);setBaseline(next);setMessage(`Saved ${saved.review_date} · ${saved.account}`);const list=await api.dailyReviews();setRecent(list.items||[]);}catch(e){setError(e.message);}finally{setSaving(false);}};
  const update=(k,v)=>setForm({...form,[k]:v});
  const images=async()=>{const r=await api.dailySummary(key.date,key.account,timeZone);const attachments=r.review?.attachments||[];setForm(v=>({...v,attachments}));setBaseline(v=>({...v,attachments}));};
  return <div className="space-y-5"><div className="flex flex-wrap items-end gap-3"><label className="text-xs text-stone-500">Journal date<input aria-label="Journal date" type="date" className="input mt-1" value={picker.date} onChange={e=>setPicker({...picker,date:e.target.value})}/></label><Choice label="Account" value={picker.account} options={[...new Set(['Main',...(options.account||[]),...recent.map(r=>r.account)])]} onChange={v=>setPicker({...picker,account:v})}/><button className="mini-btn" disabled={saving} onClick={()=>choose(picker)}>Load day</button></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status" className="text-emerald-700">{message}</p>}
    {loading?<p className="p-8 text-center text-stone-500">Loading this day...</p>:form&&<><section><h3 className="mb-3 font-semibold">{key.date} · {key.account} · automatic facts</h3><Summary data={summary}/><div className="mt-4 grid gap-3 md:grid-cols-3"><Distribution label="Instruments" value={summary.instruments?.join(', ')||'None'}/>{['sessions','setups','playbooks','grades','plan_adherence','mistakes'].map(k=><Distribution key={k} label={k.replaceAll('_',' ')} value={Object.entries(summary[k]||{}).map(([v,n])=>`${v} (${n})`).join(', ')||'None recorded'}/>)}</div></section>
    <form onSubmit={save} className="rounded-xl border bg-white p-5"><h3 className="text-lg font-semibold">Your reflection</h3><fieldset disabled={saving} className="mt-4"><div className="grid gap-4 md:grid-cols-3"><Choice label="Market condition" value={form.market_condition} options={['Trending','Ranging']} onChange={v=>update('market_condition',v)}/><Choice label="Emotional state" value={form.emotional_state} options={['Calm','Confident','Anxious','Frustrated']} onChange={v=>update('emotional_state',v)}/><Choice label="Process rating" value={form.process} options={['Great','Good','Alright','Sub-par']} onChange={v=>update('process',v)}/></div><div className="mt-5 grid gap-4 md:grid-cols-2">{[['focus_goal','Focus / goal'],['learnings','Learnings'],['mistakes','Mistakes'],['did_well','What I did well'],['improve','What needs improvement'],['actionable_steps','Actionable next steps'],['thoughts','Thoughts'],['psychology','Psychology / how I felt after']].map(([k,label])=><TextNote key={k} label={label} value={form[k]} onChange={v=>update(k,v)}/>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm text-stone-500">Earlier instrument / session / setup notes</summary><div className="mt-3 grid gap-3 md:grid-cols-3">{['pair','session','setups'].map(k=><TextNote key={k} label={k} value={form[k]} onChange={v=>update(k,v)}/>)}</div></details><button className="mt-5 rounded-md bg-stone-900 px-5 py-2 text-white">{saving?'Saving...':'Save Daily Review'}</button></fieldset>{form.id&&<Attachments ownerType="daily_review" ownerId={form.id} items={form.attachments} onChanged={images} onError={setError}/>}</form></>}
    <section><h3 className="font-semibold">Recent reviews</h3><div className="mt-3 flex flex-wrap gap-2">{recent.map(r=><button key={r.id} className="mini-btn" disabled={saving} onClick={()=>choose({date:r.review_date,account:r.account})}>{r.review_date} · {r.account}</button>)}</div>{!recent.length&&!loading&&<p className="mt-2 text-sm text-stone-500">No saved reviews yet.</p>}</section></div>;
}
function Distribution({label,value}) {return <div className="rounded-lg border bg-white p-3"><p className="text-xs capitalize text-stone-500">{label}</p><p className="mt-1 text-sm">{value}</p></div>;}
