import { useState } from 'react';
import { api } from '../../api/client';
import SymbolSearch from '../../components/SymbolSearch';
import { isoToZonedInput, nowInZoneInput } from '../../utils/timezones';
import { journalInputToIso } from './journalTime';
import { Field } from './ReviewFields';
import { useUnsaved } from './JournalShared';
const numeric=['entry_price','exit_price','quantity','position_amount','stop_loss','take_profit','fees','pnl_override'];
export default function ExecutionForm({trade,timeZone,onSaved,onCancel,onDirtyChange}) {
  const [inputZone,setInputZone]=useState(timeZone);
  const [initial]=useState(()=>({...{source:'live_manual',account:'Main',ticker:'',direction:'long',position_currency:'USD',fees:0,override_reason:''},...trade,opened_at:trade?isoToZonedInput(trade.opened_at,timeZone):nowInZoneInput(timeZone),closed_at:isoToZonedInput(trade?.closed_at,timeZone)}));
  const [form,setForm]=useState(initial),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  useUnsaved(JSON.stringify(form)!==JSON.stringify(initial)||inputZone!==timeZone,onDirtyChange);
  const set=(k,v)=>setForm({...form,[k]:v});
  const save=async e=>{e.preventDefault();setSaving(true);setError('');try{const payload=Object.fromEntries(['source','account','ticker','direction','position_currency','override_reason'].map(k=>[k,form[k]]));for(const k of numeric)payload[k]=form[k]==null||form[k]===''?null:Number(form[k]);payload.fees??=0;for(const k of ['opened_at','closed_at'])payload[k]=trade&&form[k]===initial[k]&&inputZone===timeZone?trade[k]:journalInputToIso(form[k],inputZone);const saved=trade?await api.updateJournalTrade(trade.id,payload):await api.createJournalTrade(payload);onSaved(saved);}catch(e){setError(e.message);}finally{setSaving(false);}};
  return <form onSubmit={save} className="rounded-xl border border-stone-200 bg-white p-5"><h3 className="font-semibold">{trade?'Edit execution facts':'Log a manual trade'}</h3><p className="mt-1 text-xs text-stone-500">Use actual fills. Enter quantity/units or position value; position value takes precedence over units. Initial stop and target determine planned R:R.</p>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}<fieldset disabled={saving} className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
    <Field label="Source"><select className="input" value={form.source} onChange={e=>set('source',e.target.value)}>{['live_manual','paper_manual',...(trade&&!['live_manual','paper_manual'].includes(trade.source)?[trade.source]:[])].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></Field><Field label="Account"><input required className="input" value={form.account} onChange={e=>set('account',e.target.value)}/></Field><Field label="Instrument"><SymbolSearch value={form.ticker} onChange={v=>set('ticker',v.toUpperCase())} onSelect={v=>set('ticker',v.ticker)}/></Field><Field label="Direction"><select className="input" value={form.direction} onChange={e=>set('direction',e.target.value)}><option value="long">Long</option><option value="short">Short</option></select></Field>
    <Field label="Input timezone"><select className="input" value={inputZone} onChange={e=>setInputZone(e.target.value)}>{[...new Set([timeZone,'UTC'])].map(z=><option key={z}>{z}</option>)}</select></Field>{['opened_at','closed_at'].map(k=><Field key={k} label={k==='opened_at'?'Entry time':'Exit time'}><input type="datetime-local" className="input" value={form[k]||''} onChange={e=>set(k,e.target.value)}/></Field>)}<Field label="Currency"><input required className="input" value={form.position_currency} onChange={e=>set('position_currency',e.target.value.toUpperCase())}/></Field>
    {numeric.map(k=><Field key={k} label={({stop_loss:'Initial stop',take_profit:'Initial target',pnl_override:'P&L override (optional)'})[k]||k.replaceAll('_',' ')}><input className="input" type="number" step="any" value={form[k]??''} onChange={e=>set(k,e.target.value)}/></Field>)}<Field label="Override reason"><input className="input" value={form.override_reason||''} onChange={e=>set('override_reason',e.target.value)}/></Field>
    </fieldset><div className="mt-4 flex justify-end gap-3"><button type="button" className="mini-btn" disabled={saving} onClick={onCancel}>Cancel</button><button disabled={saving} className="rounded-md bg-stone-900 px-4 py-2 text-sm text-white">{saving?'Saving…':'Save execution'}</button></div></form>;
}
