import { Field } from './ReviewFields';
import { sourceLabel } from './journalUtils';

export const emptyFilters={ticker:'',playbook_id:'',source:'',account:'',result:'',setup_grade:'',market_condition:'',session_time:'',date_from:'',date_to:''};
export default function JournalFilters({value,onChange,options={},playbooks=[]}) {
 const set=(key,v)=>onChange({...value,[key]:v});
 const select=(key,label,choices)=> <Field key={key} label={label}><select className="input" value={value[key]||''} onChange={e=>set(key,e.target.value)}><option value="">All</option>{choices.map(x=><option key={x.value??x} value={x.value??x}>{x.label??x}</option>)}</select></Field>;
 return <details className="rounded-xl border border-stone-200 bg-white p-4" open><summary className="cursor-pointer text-sm font-medium">Filter trades</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Field label="Instrument contains"><input className="input" value={value.ticker} onChange={e=>set('ticker',e.target.value)}/></Field>{select('playbook_id','Playbook',playbooks.map(p=>({value:p.id,label:p.title})))}{select('source','Source',[...new Set(['live_manual','paper_manual','replay','backtest','broker_oanda',...(options.source||[])])].map(v=>({value:v,label:sourceLabel(v)})))}{select('account','Account',options.account||[])}{select('result','Result',[{value:'win',label:'Win'},{value:'loss',label:'Loss'},{value:'breakeven',label:'Breakeven'}])}{select('setup_grade','Grade',[...new Set(['A','B','C',...(options.setup_grade||[])])])}{select('market_condition','Market condition',options.market_condition||[])}{select('session_time','Session',options.session_time||[])}{['date_from','date_to'].map(k=><Field key={k} label={k==='date_from'?'From':'To'}><input className="input" type="date" value={value[k]||''} onChange={e=>set(k,e.target.value)}/></Field>)}</div><button type="button" className="mt-3 text-xs text-blue-700" onClick={()=>onChange({...emptyFilters})}>Clear filters</button></details>;
}
