import {Section} from '../../components/ui.jsx';
import { useEffect } from 'react';
import { api, backendFileUrl } from '../../api/client';
import { pnlSummary, rValue } from './journalUtils';
export function useUnsaved(dirty, onDirtyChange) {
  useEffect(()=>{onDirtyChange?.(dirty);return()=>onDirtyChange?.(false);},[dirty,onDirtyChange]);
  useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
}
export function Summary({data={}}) {
  const value=data||{};
  const primary=[['Net P&L',pnlSummary(value)],['Total R',rValue(value.total_r)],['Win rate',value.win_rate==null?'Unavailable':`${value.win_rate.toFixed(1)}%`],['Profit factor (R)',value.profit_factor_r==='inf'?'No losses':value.profit_factor_r==null?'Unavailable':Number(value.profit_factor_r).toFixed(2)]];
  const secondary=[['N',value.trades??0],['W / L / BE',`${value.wins??0} / ${value.losses??0} / ${value.breakevens??0}`],['Average R',rValue(value.average_r)],['Avg winner',rValue(value.average_winner_r)],['Avg loser',rValue(value.average_loser_r)],['Avg hold',value.average_duration_min==null?'Unavailable':`${value.average_duration_min.toFixed(1)} min`]];
  return <section aria-label="Filtered Journal summary"><dl className="primary-metrics">{primary.map(([label,v])=><div key={label}><dt>{label}</dt><dd>{v}</dd></div>)}</dl><div className="secondary-metrics">{secondary.map(([label,v])=><span key={label}>{label} <strong>{v}</strong></span>)}</div><Section id="journal-statistics" title="More statistics"><div className="diagnostic-grid mt-3"><p>MFE {rValue(value.average_mfe_r)} (N={value.mfe_trades??0})</p><p>MAE {rValue(value.average_mae_r)} (N={value.mae_trades??0})</p><p>Plan followed {value.plan_followed_pct==null?'Unavailable':`${value.plan_followed_pct.toFixed(1)}%`} (N={value.plan_trades??0})</p><p>Grades: {Object.entries(value.grade_distribution||{}).map(([g,n])=>`${g}: ${n}`).join(', ')||'Unavailable'}</p><p>R drawdown {rValue(value.max_drawdown_r)}</p><p>Longest losing streak {value.longest_losing_streak??0}</p></div><p className="muted text-xs mt-3">R N={value.r_trades??0}; P&L N={value.pnl_trades??0}. Win rate excludes breakeven and unknown outcomes. Currency totals stay separate; missing measurements are not zero. Small samples do not establish an edge.</p></Section></section>;
}
export function Attachments({ownerType,ownerId,items=[],onChanged,onError}) {
  const act=async fn=>{try{await fn();await onChanged();}catch(e){onError(e.message);}};
  return <section className="mt-5"><div className="flex flex-wrap justify-between gap-3"><h4 className="font-semibold">Screenshots</h4><label className="cursor-pointer text-sm text-blue-700">+ Add screenshot<input className="hidden" type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)void act(()=>api.uploadJournalAttachment(ownerType,ownerId,'general',file));e.target.value='';}}/></label></div><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map(img=><div key={img.id} className="rounded-lg border p-2"><a href={backendFileUrl(img.url)} target="_blank" rel="noreferrer"><img alt={img.caption||img.original_name||'Journal screenshot'} src={backendFileUrl(img.url)} className="max-h-64 w-full bg-stone-950 object-contain"/></a><div className="mt-2 flex justify-between gap-2 text-xs"><span>{img.slot||'General'} · {img.caption||img.original_name}</span><button type="button" className="text-red-700" onClick={()=>{if(confirm('Remove this screenshot?'))void act(()=>api.deleteJournalAttachment(img.id));}}>Remove</button></div></div>)}</div>{!items.length&&<p className="mt-2 text-sm text-stone-500">No screenshots yet.</p>}</section>;
}
