import {useState} from 'react';
import {Field} from './ReviewFields';
import {FilterEditor} from '../../components/table/DataTable.jsx';
import {useUIPreference} from '../../app/useUIPreference.js';
import {filterLabel} from '../../components/table/tableModel.js';
import {sourceLabel} from './journalUtils';
export const emptyFilters={dimensions_json:'{}',date_from:'',date_to:''};
export const dimensions=[['ticker','Instrument'],['account','Account'],['external_provider','Broker'],['environment','Environment'],['source','Source'],['playbook_id','Playbook'],['setup','Setup'],['setup_grade','Grade'],['plan_followed','Plan adherence'],['direction','Direction'],['session_time','Session'],['market_condition','Market regime'],['structure_alignment','Market structure'],['entry_relativity','Entry relativity'],['shift','Shift'],['confluences','Confluences'],['mistakes','Mistakes'],['emotions','Emotion'],['weekday','Weekday'],['entry_hour','Entry hour'],['month','Month'],['result','Result']];
export default function JournalFilters({value,onChange,options={},playbooks=[],search='',onSearch,onReset,table}) {
  const selected=JSON.parse(value.dimensions_json||'{}');const [field,setField]=useState('ticker'),[open,setOpen]=useState(false),[saved,setSaved]=useUIPreference('journal.savedViews',[]);
  const set=(key,values)=>onChange({...value,dimensions_json:JSON.stringify({...selected,[key]:values||[]})});
  const label=(key,v)=>key==='source'?sourceLabel(v):key==='playbook_id'?(playbooks.find(p=>String(p.id)===v)?.title||v):v;
  return <div className="journal-filter-bar"><div className="table-toolbar"><input className="input table-search" aria-label="Search Journal" placeholder="Search trades and notes…" value={search} onChange={e=>onSearch?.(e.target.value)}/><button className="mini-btn" aria-expanded={open} onClick={()=>setOpen(!open)}>+ Filter</button><button className="mini-btn" onClick={()=>{const name=prompt('Name this Journal view');if(name?.trim())setSaved(old=>[...old.filter(v=>v.name!==name.trim()),{name:name.trim(),filters:value,search,table:table?.view}]);}}>Save view</button>{saved.length>0&&<select aria-label="Saved Journal view" className="input table-density" value="" onChange={e=>{const view=saved.find(v=>v.name===e.target.value);if(view){onChange(view.filters);onSearch?.(view.search||'');if(view.table)table?.setView(view.table);}}}><option value="">Saved views</option>{saved.map(v=><option key={v.name}>{v.name}</option>)}</select>}<button className="mini-btn" onClick={()=>{onChange({...emptyFilters});onSearch?.('');onReset?.();}}>Reset view</button></div>
    <div className="filter-chips">{Object.entries(table?.view.filters||{}).filter(([,r])=>r&&filterLabel(r)).map(([key,rule])=><button key={key} onClick={()=>table.setView(old=>({...old,filters:{...old.filters,[key]:null}}))}>{key.replaceAll('_',' ')}: {filterLabel(rule)} ×</button>)}{Object.entries(selected).flatMap(([key,values])=>values.map(v=><button key={key+v} onClick={()=>set(key,values.filter(x=>x!==v))}>{label(key,v)} ×</button>))}{['date_from','date_to'].filter(k=>value[k]).map(k=><button key={k} onClick={()=>onChange({...value,[k]:''})}>{k==='date_from'?'From':'To'} {value[k]} ×</button>)}</div>
    {open&&<section className="filter-builder"><label>Filter field<select className="input" value={field} onChange={e=>setField(e.target.value)}>{dimensions.map(([key,title])=><option key={key} value={key}>{title}</option>)}<option value="date">Date range</option></select></label>{field==='date'?<div className="ui-form-grid">{['date_from','date_to'].map(k=><Field key={k} label={k==='date_from'?'From':'To'}><input className="input" type="date" value={value[k]||''} onChange={e=>onChange({...value,[k]:e.target.value})}/></Field>)}</div>:<FilterEditor key={field} column={{key:field,label:dimensions.find(d=>d[0]===field)?.[1],kind:'category'}} values={options[field]||[]} rule={selected[field]||[]} onChange={v=>set(field,v)}/>}<p className="muted text-xs">OR within a field · AND across fields. Dates use the Journal timezone.</p><button className="mini-btn" onClick={()=>setOpen(false)}>Done</button></section>}
  </div>;
}
