import { useState } from 'react';
import { api } from '../../api/client';
import { Field, TextNote } from './ReviewFields';
import { Attachments, useUnsaved } from './JournalShared';
const blank={title:'',category:'Entry Model',description:'',rules:'',checklist:'',notes:'',sections:{},review_fields:[]};
const sections=['Process','Instruments / pairs','Time / session rules','Context','Entry model','Take-profit rules','Stop-loss rules','Risk management','Confluences','Invalidation / no-trade rules'];
export default function PlaybookView({playbooks=[],onChanged,onDirtyChange}) {
  const [form,setForm]=useState(blank),[baseline,setBaseline]=useState(blank),[error,setError]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[customSection,setCustomSection]=useState('');
  const dirty=JSON.stringify(form)!==JSON.stringify(baseline);useUnsaved(dirty,onDirtyChange);
  const choose=item=>{if(!dirty||confirm('Discard unsaved Playbook changes?')){setForm(item);setBaseline(item);setError('');setMessage('');}};
  const patch=(k,v)=>setForm({...form,[k]:v});
  const field=(id,patch)=>setForm({...form,review_fields:form.review_fields.map(f=>f.id===id?{...f,...patch}:f)});
  const save=async e=>{e.preventDefault();setSaving(true);setError('');try{const payload={...form,review_fields:form.review_fields.map(f=>({...f,options:[...new Set(f.options.map(v=>v.trim()).filter(Boolean))]}))};const saved=form.id?await api.updatePlaybook(form.id,payload):await api.createPlaybook(payload);const next={...saved,attachments:form.attachments||[]};setForm(next);setBaseline(next);setMessage('Playbook saved.');onChanged();}catch(e){setError(e.message);}finally{setSaving(false);}};
  const remove=async()=>{if(!confirm('Delete this Playbook and its screenshots? Existing trade reviews will retain their answers.'))return;try{await api.deletePlaybook(form.id);setForm(blank);setBaseline(blank);onChanged();}catch(e){setError(e.message);}};
  const reloadImages=async()=>{const r=await api.playbook();const images=r.items.find(x=>x.id===form.id)?.attachments||[];setForm(v=>({...v,attachments:images}));setBaseline(v=>({...v,attachments:images}));onChanged();};
  return <div className="grid gap-5 lg:grid-cols-[260px_minmax(0,1fr)]"><aside className="rounded-xl border bg-white p-4"><div className="flex justify-between"><h3 className="font-semibold">Your Playbooks</h3><button className="text-sm text-blue-700" disabled={saving} onClick={()=>choose(blank)}>+ New</button></div><p className="mt-2 text-xs text-stone-500">Human trading plans and examples. Each plan can ask different review questions.</p><div className="mt-4 space-y-2">{playbooks.map(p=><button key={p.id} disabled={saving} className={`block w-full rounded-lg border p-3 text-left ${form.id===p.id?'border-blue-500 bg-blue-50':'border-stone-200'}`} onClick={()=>choose({...blank,...p})}><strong className="text-sm">{p.title}</strong><p className="text-xs text-stone-500">{p.category}</p></button>)}</div>{!playbooks.length&&<p className="mt-5 text-sm text-stone-500">Create your first trading plan.</p>}</aside>
    <form onSubmit={save} className="min-w-0 rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><h3 className="text-xl font-semibold">{form.id?form.title:'New Playbook'}</h3>{form.id&&<button type="button" disabled={saving} className="text-xs text-red-700" onClick={remove}>Delete</button>}</div>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}{message&&<p role="status" className="mt-3 text-emerald-700">{message}</p>}<fieldset disabled={saving} className="mt-5 space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Title"><input required className="input" value={form.title} onChange={e=>patch('title',e.target.value)}/></Field><Field label="Category"><input className="input" value={form.category} onChange={e=>patch('category',e.target.value)}/></Field></div><TextNote label="Description" value={form.description} onChange={v=>patch('description',v)}/>
    <div className="grid gap-4 md:grid-cols-2">{[...new Set([...sections,...Object.keys(form.sections)])].map(k=><TextNote key={k} label={k} value={form.sections[k]} onChange={v=>patch('sections',{...form.sections,[k]:v})}/>)}</div><div className="flex gap-2"><input aria-label="New section title" className="input" value={customSection} onChange={e=>setCustomSection(e.target.value)} placeholder="Add a section title"/><button type="button" className="mini-btn" onClick={()=>{if(customSection.trim()){patch('sections',{...form.sections,[customSection.trim()]:form.sections[customSection.trim()]||''});setCustomSection('');}}}>Add section</button></div>
    <div className="grid gap-4 md:grid-cols-2"><TextNote label="Rules (existing freeform)" value={form.rules} onChange={v=>patch('rules',v)}/><TextNote label="Checklist" value={form.checklist} onChange={v=>patch('checklist',v)}/><TextNote label="Notes" value={form.notes} onChange={v=>patch('notes',v)}/></div>
    <section className="border-t pt-5"><h4 className="font-semibold">Trade review questions</h4><p className="mt-1 text-xs text-stone-500">Shown when a trade links to this Playbook. Renaming a question preserves answers; removing one keeps earlier answers visible on the trade.</p><div className="mt-4 space-y-4">{form.review_fields.map(f=><div key={f.id} className="rounded-lg border p-4"><div className="grid gap-3 md:grid-cols-2"><Field label="Question"><input required className="input" value={f.label} onChange={e=>field(f.id,{label:e.target.value})}/></Field><Field label="Answer type"><select className="input" value={f.type} onChange={e=>field(f.id,{type:e.target.value})}><option value="select">Single choice</option><option value="multi">Multiple choices</option><option value="text">Free text</option></select></Field></div>{f.type!=='text'&&<div className="mt-3"><TextNote label="Options (one per line)" value={f.options.join('\n')} onChange={v=>field(f.id,{options:v.split('\n')})}/><label className="mt-2 block text-sm"><input type="checkbox" checked={f.allow_custom} onChange={e=>field(f.id,{allow_custom:e.target.checked})}/> Allow custom answers</label></div>}<button type="button" className="mt-3 text-xs text-red-700" onClick={()=>patch('review_fields',form.review_fields.filter(x=>x.id!==f.id))}>Remove question</button></div>)}</div><button type="button" className="mini-btn mt-3" onClick={()=>patch('review_fields',[...form.review_fields,{id:crypto.randomUUID(),label:'',type:'select',options:[],allow_custom:true}])}>+ Add review question</button></section>
    <div className="flex justify-end"><button disabled={saving} className="rounded-md bg-stone-900 px-5 py-2 text-white">{saving?'Saving...':'Save Playbook'}</button></div></fieldset>{form.id&&<Attachments ownerType="playbook" ownerId={form.id} items={form.attachments} onChanged={reloadImages} onError={setError}/>}</form></div>;
}
