import { useEffect, useState } from "react";
import { api, backendFileUrl } from "../../api/client";

const blank = { title: "", category: "Entry Model", description: "", rules: "", checklist: "", notes: "" };
export default function PlaybookView() {
  const [items, setItems] = useState([]); const [selectedId, setSelectedId] = useState(null); const [form, setForm] = useState(blank); const [error, setError] = useState(""); const [uploading, setUploading] = useState(false);
  const load = async () => { try { const r = await api.playbook(); setItems(r.items || []); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, []);
  const selected = items.find((x) => x.id === selectedId) || null;
  useEffect(() => { if (selected) setForm({ title: selected.title, category: selected.category, description: selected.description, rules: selected.rules, checklist: selected.checklist, notes: selected.notes }); }, [selectedId]);
  const save = async (e) => { e.preventDefault(); setError(""); try { if (selected) await api.updatePlaybook(selected.id, form); else { const created = await api.createPlaybook(form); await load(); setSelectedId(created.id); setForm({ title: created.title, category: created.category, description: created.description, rules: created.rules, checklist: created.checklist, notes: created.notes }); return; } await load(); } catch (e2) { setError(e2.message); } };
  const remove = async () => { if (!selected || !confirm("Delete this playbook entry and its images?")) return; await api.deletePlaybook(selected.id); setSelectedId(null); setForm(blank); await load(); };
  const upload = async (file) => { if (!file || !selected) return; setUploading(true); try { await api.uploadJournalAttachment("playbook", selected.id, "example", file); await load(); } catch (e) { setError(e.message); } finally { setUploading(false); } };
  return <div className="grid gap-6 xl:grid-cols-[360px_minmax(0,1fr)]">
    <aside className="rounded-xl border border-stone-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-semibold">Playbook</h3><button onClick={() => { setSelectedId(null); setForm(blank); }} className="text-sm text-blue-700">+ New</button></div><p className="mt-1 text-xs text-stone-500">Your plan/reference material: entry models, process, risk rules and examples. This is separate from trades you actually took.</p><div className="mt-4 space-y-2">{items.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`block w-full rounded-md border p-3 text-left ${selectedId === item.id ? "border-stone-700 bg-stone-50" : "border-stone-100 hover:bg-stone-50"}`}><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-stone-500">{item.category}</p></button>)}</div></aside>
    <form onSubmit={save} className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h3 className="text-xl font-semibold">{selected ? selected.title : "New playbook entry"}</h3><p className="mt-1 text-sm text-stone-500">Use this for content like your Type 1/2/3 Shift definitions, checklists, stop rules and examples.</p></div>{selected && <button type="button" onClick={remove} className="text-xs text-red-700">Delete</button>}</div>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Title"><input required className="input" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Type 3 Shift" /></Field><Field label="Category"><input className="input" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="Entry Model" /></Field></div>
      <div className="mt-4 space-y-4"><Long label="Description" value={form.description} set={(v) => setForm({ ...form, description: v })} /><Long label="Rules" value={form.rules} set={(v) => setForm({ ...form, rules: v })} placeholder="One rule per line…" /><Long label="Checklist" value={form.checklist} set={(v) => setForm({ ...form, checklist: v })} placeholder="Direction\nAOI\nEntry model\nConfluences…" /><Long label="Notes" value={form.notes} set={(v) => setForm({ ...form, notes: v })} /></div>
      {selected && <div className="mt-5 border-t border-stone-100 pt-4"><div className="flex items-center justify-between"><h4 className="font-semibold">Example images</h4><label className="cursor-pointer text-sm text-blue-700">{uploading ? "Uploading…" : "+ Add image"}<input type="file" accept="image/*" className="hidden" onChange={(e) => upload(e.target.files?.[0])} /></label></div><div className="mt-3 grid gap-3 md:grid-cols-2">{(selected.attachments || []).map((img) => <img key={img.id} src={backendFileUrl(img.url)} className="max-h-80 w-full rounded-md border bg-stone-950 object-contain" />)}</div></div>}
      <div className="mt-5 flex justify-end"><button className="rounded-md bg-stone-900 px-5 py-2 text-sm text-white">{selected ? "Save playbook" : "Create playbook entry"}</button></div>
    </form>
  </div>;
}
function Field({ label, children }) { return <label><span className="mb-1 block text-xs font-medium text-stone-500">{label}</span>{children}</label>; }
function Long({ label, value, set, placeholder }) { return <Field label={label}><textarea rows="5" className="input resize-y" value={value || ""} onChange={(e) => set(e.target.value)} placeholder={placeholder} /></Field>; }
