import { useId, useState } from "react";

export function Field({label, children}) { return <label className="block min-w-0"><span className="mb-1 block text-xs font-medium text-stone-500">{label}</span>{children}</label>; }
export function Choice({label, value, options = [], onChange}) {
  const id=useId();
  return <Field label={label}><input className="input" list={id} value={value || ""} onChange={e=>onChange(e.target.value)} placeholder="Choose or enter your own"/><datalist id={id}>{[...new Set(options)].map(v=><option key={v} value={v}/>)}</datalist></Field>;
}
export function Chips({label, value = [], options = [], onChange, allowCustom = true}) {
  const [custom,setCustom]=useState(""); const values=Array.isArray(value)?value:[];
  const toggle=v=>onChange(values.includes(v)?values.filter(x=>x!==v):[...values,v]);
  return <div><p className="mb-2 text-xs font-medium text-stone-500">{label}</p><div className="flex flex-wrap gap-2">{[...new Set([...options,...values])].map(v=><button type="button" aria-pressed={values.includes(v)} key={v} onClick={()=>toggle(v)} className={`rounded-full border px-3 py-1.5 text-xs ${values.includes(v)?"border-blue-500 bg-blue-50 text-blue-800":"border-stone-200 text-stone-600"}`}>{v}</button>)}</div>{allowCustom&&<div className="mt-2 flex gap-2"><input aria-label={`Custom ${label}`} className="input" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Add your own" onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();if(custom.trim()){onChange([...new Set([...values,custom.trim()])]);setCustom("")}}}}/><button type="button" className="mini-btn" onClick={()=>{if(custom.trim()){onChange([...new Set([...values,custom.trim()])]);setCustom("")}}}>Add</button></div>}</div>;
}
export function TextNote({label,value,onChange}) { return <Field label={label}><textarea className="input resize-y" rows={3} value={value || ""} onChange={e=>onChange(e.target.value)}/></Field>; }

export default function ReviewFields({draft, setDraft, playbooks=[]}) {
  const data=draft.review_data || {}; const patch=(key,value)=>setDraft({...draft,[key]:value});
  const review=(key,value)=>patch("review_data",{...data,[key]:value});
  const book=playbooks.find(p=>p.id===Number(draft.playbook_id));
  const custom=data.custom || {}; const definitions=book?.review_fields || [];
  const activeKeys=definitions.map(f=>`${book.id}:${f.id}`);
  const answer=(key,value,label)=>patch("review_data",{...data,custom:{...custom,[key]:value},custom_labels:{...(data.custom_labels||{}),[key]:label}});
  return <div className="space-y-6">
    <div className="grid gap-4 md:grid-cols-3"><Field label="Playbook"><select className="input" value={draft.playbook_id || ""} onChange={e=>patch('playbook_id',e.target.value?Number(e.target.value):null)}><option value="">No Playbook linked</option>{playbooks.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></Field><Choice label="Setup quality" value={draft.setup_grade} options={["A","B","C"]} onChange={v=>patch('setup_grade',v)}/><Field label="Plan followed"><div className="flex flex-wrap gap-2">{["Yes","Partially","No"].map(v=><button type="button" key={v} aria-pressed={draft.plan_followed===v} className={`mini-btn ${draft.plan_followed===v?'active-btn':''}`} onClick={()=>patch('plan_followed',draft.plan_followed===v?'':v)}>{v}</button>)}</div></Field></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Choice label="Market condition" value={draft.market_condition} options={["Trending","Ranging"]} onChange={v=>patch('market_condition',v)}/><Choice label="Structure alignment" value={data.structure_alignment} options={["Aligned","Mixed","Countertrend"]} onChange={v=>review('structure_alignment',v)}/><Choice label="AOI / context timeframe" value={data.context_timeframe} options={["5m","15m","30m","1h","4h","1d"]} onChange={v=>review('context_timeframe',v)}/><Choice label="Entry relativity" value={data.entry_relativity} onChange={v=>review('entry_relativity',v)}/><Choice label="Setup" value={draft.setup} onChange={v=>patch('setup',v)}/><Choice label="Shift" value={data.shift} onChange={v=>review('shift',v)}/><Choice label="Session" value={draft.session_time} options={["Asia","London","New York"]} onChange={v=>patch('session_time',v)}/></div>
    <div className="grid gap-5 lg:grid-cols-3"><Chips label="Confluences / correlations" value={data.confluences} onChange={v=>review('confluences',v)}/><Chips label="Mistakes" value={data.mistakes} options={["Early entry","Overtrading","Moved stop","Missed plan"]} onChange={v=>review('mistakes',v)}/><Chips label="Emotions" value={data.emotions} options={["Calm","Confident","Anxious","Frustrated"]} onChange={v=>review('emotions',v)}/></div>
    {definitions.length>0&&<section className="rounded-lg border border-stone-200 p-4"><h4 className="mb-4 font-medium">{book.title} · review</h4><div className="grid gap-4 md:grid-cols-2">{definitions.map(f=>{const key=`${book.id}:${f.id}`;return f.type==='multi'?<Chips key={key} label={f.label} value={custom[key]} options={f.options} allowCustom={f.allow_custom} onChange={v=>answer(key,v,f.label)}/>:f.type==='select'&&!f.allow_custom?<Field key={key} label={f.label}><select className="input" value={custom[key]||""} onChange={e=>answer(key,e.target.value,f.label)}><option value="">Not reviewed</option>{[...new Set([...(f.options||[]),custom[key]].filter(Boolean))].map(v=><option key={v}>{v}</option>)}</select></Field>:<Choice key={key} label={f.label} value={custom[key]} options={f.type==='select'?f.options:[]} onChange={v=>answer(key,v,f.label)}/>})}</div></section>}
    {Object.keys(custom).some(k=>!activeKeys.includes(k))&&<details><summary className="cursor-pointer text-sm text-stone-500">Earlier Playbook answers</summary><div className="mt-3 grid gap-3 md:grid-cols-2">{Object.entries(custom).filter(([k])=>!activeKeys.includes(k)).map(([k,v])=><div key={k} className="rounded border p-3 text-sm"><strong>{data.custom_labels?.[k] || k}</strong><p>{Array.isArray(v)?v.join(', '):String(v??'')}</p></div>)}</div></details>}
    <div className="grid gap-4 md:grid-cols-2"><TextNote label="What I saw / analysis" value={draft.analysis} onChange={v=>patch('analysis',v)}/><TextNote label="Entry reasoning" value={draft.entry_notes} onChange={v=>patch('entry_notes',v)}/><TextNote label="What went well" value={data.went_well} onChange={v=>review('went_well',v)}/><TextNote label="What went wrong" value={data.went_wrong} onChange={v=>review('went_wrong',v)}/><TextNote label="What I would do differently" value={data.do_differently} onChange={v=>review('do_differently',v)}/><TextNote label="Management" value={draft.management} onChange={v=>patch('management',v)}/><TextNote label="Learning" value={draft.learning} onChange={v=>patch('learning',v)}/><TextNote label="Notes" value={draft.notes} onChange={v=>patch('notes',v)}/></div>
    <details><summary className="cursor-pointer text-sm text-stone-500">Earlier review fields</summary><div className="mt-3 grid gap-3 md:grid-cols-3">{['trade_type','entry_timeframe','timeframe_alignment','dxy','tf_type','wick'].map(k=><Choice key={k} label={k.replaceAll('_',' ')} value={draft[k]} onChange={v=>patch(k,v)}/>)}</div></details>
  </div>;
}
