import { useEffect, useState } from 'react';
import { api } from '../../api/client';
import { formatInZone } from '../../utils/timezones';
import { moneyCurrency, rValue, rrValue, sourceLabel } from './journalUtils';
import ReviewFields, { TextNote } from './ReviewFields';
import { Attachments, useUnsaved } from './JournalShared';
import ExecutionForm from './ExecutionForm';
const reviewKeys=['playbook_id','setup_grade','plan_followed','review_data','trade_type','setup','market_condition','entry_timeframe','timeframe_alignment','dxy','session_time','tf_type','wick','analysis','entry_notes','management','learning','notes','timeframe_notes'];
export default function TradeDetail({trade,timeZone,playbooks,revision,onChanged,onClose,onDirtyChange}) {
  const [facts,setFacts]=useState(trade),[draft,setDraft]=useState(trade),[baseline,setBaseline]=useState(trade),[edit,setEdit]=useState(false),[executionDirty,setExecutionDirty]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{let active=true;api.journalTrade(trade.id).then(t=>{if(active)setFacts(t);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[trade.id,revision]);
  const dirty=JSON.stringify(draft)!==JSON.stringify(baseline);
  useUnsaved(dirty||executionDirty,onDirtyChange);
  const broker=facts.source.startsWith('broker_'), currency=facts.account_currency||facts.position_currency||'USD';
  const duration=facts.closed_at&&facts.opened_at?(Date.parse(facts.closed_at)-Date.parse(facts.opened_at))/60000:null;
  const money=v=>moneyCurrency(v,currency);
  const metrics=[['Entry time',formatInZone(facts.opened_at,timeZone)],['Exit time',formatInZone(facts.closed_at,timeZone)],['Entry price',facts.entry_price],['Weighted exit price',facts.exit_price],['Initial stop',facts.stop_loss],['Initial target',facts.take_profit],['Quantity / units',facts.quantity],['Account currency',currency],['Recorded P&L',money(facts.pnl_amount)],['Realised R',rValue(facts.r_multiple)],['Planned R:R',rrValue(facts.planned_rr)],['Duration',duration==null?'—':`${duration.toFixed(1)} min`],['P&L source',facts.pnl_source||'Unknown'],['Session (review)',draft.session_time||'Unlabelled'],...(broker?[['Broker realised P&L',money(facts.broker_realized_pnl)],['Commission',money(facts.commission)],['Financing',money(facts.financing)],['Guaranteed execution fee',money(facts.guaranteed_execution_fee)],['Dividend adjustment',money(facts.dividend_adjustment)],['Initial risk',money(facts.initial_risk_amount)]]:[['Fees',money(facts.fees)]])];
  const save=async()=>{setSaving(true);setError('');setMessage('');try{const updated=await api.updateJournalTrade(facts.id,Object.fromEntries(reviewKeys.filter(k=>draft[k]!==undefined).map(k=>[k,draft[k]])));setDraft(updated);setBaseline(updated);setFacts({...updated,attachments:facts.attachments});setMessage('Review saved.');onChanged();}catch(e){setError(e.message);}finally{setSaving(false);}};
  const refreshAttachments=async()=>{const latest=await api.journalTrade(facts.id);setFacts(current=>({...current,attachments:latest.attachments}));};
  return <section className="rounded-xl border border-stone-300 bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-stone-500">{sourceLabel(facts.source)} · {facts.account}</p><h3 className="mt-1 text-2xl font-semibold">{facts.ticker} · {facts.direction}</h3></div><button className="mini-btn" disabled={saving} onClick={onClose}>Close details</button></div>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}{message&&<p role="status" className="mt-3 text-emerald-700">{message}</p>}
    <h4 className="mb-3 mt-6 font-semibold">Execution facts {broker&&<span className="text-xs font-normal text-stone-500">&middot; supplied by OANDA &middot; read only</span>}</h4><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label,value])=><div className="rounded-lg bg-stone-50 p-3" key={label}><p className="text-xs text-stone-500">{label}</p><p className="mt-1 break-words text-sm font-medium">{value??'Unavailable'}</p></div>)}</div>
    {broker&&(!facts.costs_complete||facts.r_multiple==null)&&<p className="mt-3 text-xs text-stone-500">Net P&L requires attributable costs. R additionally requires reliable initial risk; unavailable values are not estimated.</p>}
    {!broker&&<button className="mini-btn mt-4" onClick={()=>{if(!edit||!executionDirty||confirm('Discard execution changes?'))setEdit(v=>!v);}}>{edit?'Hide execution editor':'Edit execution facts'}</button>}
    {edit&&<div className="mt-4"><ExecutionForm trade={facts} timeZone={timeZone} onDirtyChange={setExecutionDirty} onCancel={()=>{if(!executionDirty||confirm('Discard execution changes?'))setEdit(false);}} onSaved={updated=>{setFacts({...updated,attachments:facts.attachments});setEdit(false);setExecutionDirty(false);onChanged();}}/></div>}
    <fieldset disabled={saving} className="mt-7 border-t pt-5"><div className="mb-5 flex items-center justify-between"><h4 className="text-lg font-semibold">Your review</h4><button className="rounded-md bg-stone-900 px-4 py-2 text-sm text-white" onClick={save}>{saving?'Saving...':'Save review'}</button></div><ReviewFields draft={draft} setDraft={setDraft} playbooks={playbooks}/><details className="mt-5"><summary className="cursor-pointer text-sm">Timeframe notes</summary><div className="mt-3 grid gap-4 md:grid-cols-2">{[...new Set(['1m','5m','15m','30m','1H','4H',...Object.keys(draft.timeframe_notes||{})])].map(tf=><TextNote key={tf} label={tf} value={draft.timeframe_notes?.[tf]} onChange={v=>setDraft({...draft,timeframe_notes:{...draft.timeframe_notes,[tf]:v}})}/>)}</div></details></fieldset>
    <Attachments ownerType="trade" ownerId={facts.id} items={facts.attachments} onChanged={refreshAttachments} onError={setError}/>
    {broker&&<details className="mt-5"><summary className="cursor-pointer text-xs text-stone-500">Imported execution provenance</summary><pre className="mt-2 max-h-72 overflow-auto rounded bg-stone-50 p-3 text-xs">{JSON.stringify(facts.source_metadata,null,2)}</pre></details>}
  </section>;
}
