import { useEffect, useState } from 'react';
import { api } from '../../api/client';
import { formatInZone } from '../../utils/timezones';
import { moneyCurrency, sourceLabel, rValue, resultTone } from './journalUtils';
import TradeDetail from './TradeDetail';
import ExecutionForm from './ExecutionForm';
import { Summary, useUnsaved } from './JournalShared';
export default function TradesView({filters,timeZone,playbooks,revision,onChanged,onDirtyChange}) {
  const [rows,setRows]=useState([]),[summary,setSummary]=useState({}),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[view,setView]=useState('cards'),[selected,setSelected]=useState(null),[creating,setCreating]=useState(false),[dirty,setDirty]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const query=JSON.stringify(filters);
  useUnsaved(dirty,onDirtyChange);
  useEffect(()=>{setOffset(0);},[query]);
  useEffect(()=>{let active=true;setLoading(true);setError('');Promise.all([api.journalTrades({...JSON.parse(query),limit:50,offset}),api.journalAnalytics(JSON.parse(query))]).then(([t,a])=>{if(active){setRows(t.items);setTotal(t.total);setSummary(a);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query,offset,revision]);
  const navigate=fn=>{if(!dirty||confirm('Discard unsaved trade changes?')){setDirty(false);fn();}};
  const open=async id=>{try{setSelected(await api.journalTrade(id));setCreating(false);}catch(e){setError(e.message);}};
  const remove=async t=>{if(!confirm('Delete this Journal record and its screenshots?'))return;try{await api.deleteJournalTrade(t.id);if(selected?.id===t.id)setSelected(null);onChanged();}catch(e){setError(e.message);}};
  const facts=t=><><span className={resultTone(t.result)}>{t.result||t.status}</span><span>{moneyCurrency(t.pnl_amount,t.account_currency||t.position_currency||'USD')}</span><span>{rValue(t.r_multiple)}</span></>;
  return <div className="space-y-5"><Summary data={summary}/><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-stone-500">{total} matching trades</p><div className="flex gap-2">{['cards','table'].map(v=><button key={v} className={`mini-btn ${view===v?'active-btn':''}`} onClick={()=>setView(v)}>{v==='cards'?'Cards':'Table'}</button>)}<button className="mini-btn" onClick={()=>navigate(()=>{setCreating(true);setSelected(null);})}>+ Log trade</button></div></div>
    {error&&<p role="alert" className="rounded border border-red-200 p-3 text-red-700">{error}</p>}
    {creating&&<ExecutionForm timeZone={timeZone} onDirtyChange={setDirty} onCancel={()=>navigate(()=>setCreating(false))} onSaved={t=>{setDirty(false);setCreating(false);setSelected(t);onChanged();}}/>}
    {selected&&<TradeDetail key={selected.id} trade={selected} timeZone={timeZone} playbooks={playbooks} revision={revision} onDirtyChange={setDirty} onClose={()=>navigate(()=>setSelected(null))} onChanged={onChanged}/>}
    {loading?<p role="status" className="p-8 text-center text-stone-500">Loading trades...</p>:!rows.length?<div className="rounded-xl border border-dashed p-10 text-center"><h3 className="font-medium">No trades match these filters</h3><p className="mt-2 text-sm text-stone-500">Clear filters, log a manual trade, finish a Replay trade, or sync a configured broker.</p></div>:view==='cards'?<div className="grid gap-4 lg:grid-cols-2">{rows.map(t=><article key={t.id} className="rounded-xl border border-stone-200 bg-white p-5"><div className="flex justify-between gap-3"><div><button className="text-lg font-semibold text-blue-700" onClick={()=>navigate(()=>void open(t.id))}>{t.ticker} · {t.direction}</button><p className="mt-1 text-xs text-stone-500">{sourceLabel(t.source)} · {t.account}</p></div><span className="text-sm">{t.setup_grade&&`Grade ${t.setup_grade}`}</span></div><p className="mt-3 text-sm text-stone-600">{formatInZone(t.opened_at,timeZone)} · {t.playbook_title||t.setup||'No Playbook linked'}</p><div className="mt-3 flex flex-wrap gap-4 font-medium">{facts(t)}</div><div className="mt-4 flex justify-between text-xs"><button className="text-blue-700" onClick={()=>navigate(()=>void open(t.id))}>Open review</button><button className="text-stone-500" onClick={()=>navigate(()=>void remove(t))}>Delete</button></div></article>)}</div>:<div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{['Entry','Instrument','Source / account','Playbook / grade','Outcome / P&L / R',''].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(t=><tr key={t.id} className="border-t"><td className="p-3">{formatInZone(t.opened_at,timeZone)}</td><td className="p-3"><button className="font-medium text-blue-700" onClick={()=>navigate(()=>void open(t.id))}>{t.ticker} · {t.direction}</button></td><td className="p-3">{sourceLabel(t.source)}<br/>{t.account}</td><td className="p-3">{t.playbook_title||'Unlinked'} / {t.setup_grade||'—'}</td><td className="space-x-3 p-3">{facts(t)}</td><td><button className="p-3 text-xs text-red-700" onClick={()=>navigate(()=>void remove(t))}>Delete</button></td></tr>)}</tbody></table></div>}
    <div className="flex items-center justify-end gap-3 text-sm"><button className="mini-btn" disabled={loading||!offset} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><span>{total?`${offset+1}–${Math.min(offset+50,total)} of ${total}`:'0 trades'}</span><button className="mini-btn" disabled={loading||offset+50>=total} onClick={()=>setOffset(offset+50)}>Next</button></div>
  </div>;
}
