import {Section} from '../../components/ui.jsx';
﻿import {useMemo,useState} from 'react';
import {api} from '../../api/client';
import BrokerProfilesPanel from '../brokers/BrokerProfilesPanel';
import {moneyCurrency} from '../journal/journalUtils';
import {activitySemantics,brokerDate,percent,positionMetrics,returnPercent} from './brokerPortfolioUtils';
import {usePortfolioSnapshot} from './usePortfolioSnapshot.js';
import DataTable from '../../components/table/DataTable.jsx';
const amount=(value,currency)=>Number.isFinite(value)&&currency?`${moneyCurrency(value,currency)} ${currency}`:'Unavailable';
export default function BrokerPortfolioPanel() {
  const [revision,setRevision]=useState(0),[selected,setSelected]=useState(null),[note,setNote]=useState(''),[tags,setTags]=useState('');
  const {accounts,account,setAccount,kind,setKind,data,error,setError,loading}=usePortfolioSnapshot(revision);
  const change=fn=>{if(!selected||confirm('Discard unsaved Portfolio review changes?')){setSelected(null);fn();}};
  const save=async()=>{try{await api.saveBrokerPortfolioReview(selected.id,{note,tags:tags.split(',').map(x=>x.trim()).filter(Boolean)});setSelected(null);setRevision(v=>v+1);}catch(e){setError(e.message);}};
  const current=accounts.find(a=>a.account_key===account),s=current?.summary||{},currency=s.currency,zone=localStorage.getItem('ledger.timeZone')||'UTC';
  const review=r=>change(()=>{setSelected(r);setNote(r.note||'');setTags((r.tags||[]).join(', '));});
  const rows=useMemo(()=>data.items.map(r=>{const f=r.facts,o=f.order||{},fill=f.fill||{},inst=f.instrument||o.instrument||{},wallet=f.walletImpact||fill.walletImpact||{},sem=activitySemantics(f,kind);return {...r,...positionMetrics(f),name:(inst.name||inst.ticker||f.ticker||o.ticker||sem.type)+(kind==='position'&&!r.active?' (previous snapshot)':''),type:sem.type,direction:sem.direction,quantity:f.quantity??fill.quantity??o.quantity,date:fill.filledAt||f.paidOn||f.dateTime||f.createdAt||o.createdAt,price:fill.price,priceCurrency:inst.currency||o.currency,value:kind==='position'?f.walletImpact?.currentValue:f.amount??wallet.netValue,walletCurrency:kind==='position'?f.walletImpact?.currency:f.currency||wallet.currency};}),[data,kind]);
  const columns=useMemo(()=>{
    const definitions=kind==='position'?[['name','Instrument','text'],['ticker','Ticker','category'],['quantity','Shares','number'],['averageCost','Average cost','number'],['currentPrice','Current price','number'],['invested','Open cost','number'],['value','Current value','number'],['pnl','Unrealised P&L','number'],['returnPct','Return %','number']]:[['name',kind==='orders'?'Instrument':'Type / instrument','text'],['direction',kind==='orders'?'Action':'Direction','category'],['date','Date/time','date'],...(kind==='orders'?[['quantity','Quantity','number'],['price','Execution price','number']]:[]),['value','Reported value','number'],['walletCurrency','Currency','category']];
    return definitions.map(([key,label,kind])=>({key,label,kind,sticky:key==='name',render:r=>key==='date'?brokerDate(r.date,zone):key==='returnPct'?percent(r.returnPct):['averageCost','currentPrice','price'].includes(key)?amount(r[key],r.priceCurrency):['invested','value','pnl'].includes(key)?amount(r[key],r.walletCurrency):key==='direction'?<span className={['BUY','IN'].includes(r.direction)?'positive':['SELL','OUT'].includes(r.direction)?'negative':''}>{r.direction}</span>:r[key]??'Unavailable'}));
  },[kind,zone]);
  const metrics=[['Account value',amount(s.totalValue,currency)],['Invested / open cost',amount(s.investments?.totalCost,currency)],['Unrealised P&L',amount(s.investments?.unrealizedProfitLoss,currency)],['Unrealised return',percent(currency?returnPercent(s.investments?.unrealizedProfitLoss,s.investments?.totalCost):null)],['Realised P&L',amount(s.investments?.realizedProfitLoss,currency)],['Cash',amount(s.cash?.availableToTrade,currency)]];
  return <section className="mt-5"><Section id="portfolio-connections" title="Broker connections and auto-sync"><BrokerProfilesPanel destination="portfolio" onSynced={()=>setRevision(v=>v+1)}/></Section>{error&&<p role="alert" className="text-red-700">{error}</p>}{!current?<p className="empty-state">Connect a read-only broker to view your Portfolio snapshot.</p>:<>
    <div className="table-toolbar"><h3 className="font-semibold">Broker Portfolio snapshot</h3><label>Account <select className="input table-density" value={account} onChange={e=>change(()=>setAccount(e.target.value))}>{accounts.map(a=><option key={a.account_key} value={a.account_key}>{a.label}</option>)}</select></label></div>
    <dl className="portfolio-metrics">{metrics.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="muted text-xs mt-2">As of {brokerDate(current.synced_at,zone)} ({zone}). Prices retain instrument currency; wallet values retain account currency. Unrealised return = P&L / open cost. Historical activity does not add to holdings.</p>
    <nav className="feature-nav" aria-label="Portfolio records">{[['position','Positions'],['orders','Orders / fills'],['dividends','Dividends'],['transactions','Cash transactions']].map(([key,label])=><button key={key} aria-current={kind===key?'page':undefined} onClick={()=>change(()=>setKind(key))}>{label}</button>)}</nav>
    {selected&&<section className="insight-panel mb-4"><div className="ui-toolbar"><h4 className="font-semibold">{selected.name||'Record'} · Notes and details</h4><button className="mini-btn" onClick={()=>change(()=>setSelected(null))}>Close</button></div><label className="block text-sm">Note<textarea className="input" value={note} onChange={e=>setNote(e.target.value)}/></label><label className="block text-sm">Tags (comma separated)<input className="input" value={tags} onChange={e=>setTags(e.target.value)}/></label><button className="mini-btn mt-2" onClick={save}>Save Portfolio review</button><details className="ui-section"><summary>Provider facts and timestamps</summary><p className="text-xs break-all">Provider ID: {selected.external_id}</p><pre className="text-xs whitespace-pre-wrap break-all">{JSON.stringify(selected.facts,null,2)}</pre></details></section>}
    {loading&&<p className="muted text-xs">Updating snapshot…</p>}
    <DataTable key={account+kind} id={`portfolio.${kind}`} label={kind==='position'?'Portfolio positions':kind==='orders'?'Orders and fills':'Cash activity'} rows={rows} columns={columns} primaryAction={{label:'Details',onClick:review}} actions={r=>[{label:'Notes / tags',onClick:()=>review(r)}]} summary={visible=>{const holdings=visible.filter(r=>r.active&&kind==='position'),totals={};for(const r of holdings)if(Number.isFinite(r.value)&&r.walletCurrency)totals[r.walletCurrency]=(totals[r.walletCurrency]||0)+r.value;return <p className="px-3 pb-3 text-xs muted">N = {visible.length} matching records{kind==='position'?` · ${holdings.length} active holdings · ${Object.entries(totals).map(([c,v])=>amount(v,c)).join(' / ')||'Value unavailable'}`:' · Activity is not an account return calculation'}</p>;}}/>
  </>}</section>;
}
