import {useEffect,useState} from 'react';
import {api} from '../../api/client';
import BrokerProfilesPanel from '../brokers/BrokerProfilesPanel';
import {moneyCurrency} from '../journal/journalUtils';

export default function BrokerPortfolioPanel() {
  const [accounts,setAccounts]=useState([]),[account,setAccount]=useState(''),[kind,setKind]=useState('position'),[offset,setOffset]=useState(0),[data,setData]=useState({items:[],total:0}),[revision,setRevision]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false),[selected,setSelected]=useState(null),[note,setNote]=useState(''),[tags,setTags]=useState('');
  useEffect(()=>{let active=true;api.brokerPortfolioAccounts().then(r=>{if(active){setAccounts(r.items);setAccount(a=>a||r.items[0]?.account_key||'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[revision]);
  useEffect(()=>{if(!account)return;let active=true;setLoading(true);api.brokerPortfolioRecords(account,kind,offset).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[account,kind,offset,revision]);
  const change=fn=>{if(!selected||confirm('Discard unsaved Portfolio review changes?')){setSelected(null);fn();}};
  const save=async()=>{try{await api.saveBrokerPortfolioReview(selected.id,{note,tags:tags.split(',').map(x=>x.trim()).filter(Boolean)});setSelected(null);setRevision(v=>v+1);}catch(e){setError(e.message);}};
  const current=accounts.find(a=>a.account_key===account),s=current?.summary||{},currency=s.currency;
  return <section className="mt-5"><BrokerProfilesPanel destination="portfolio" onSynced={()=>setRevision(v=>v+1)}/>{error&&<p role="alert" className="text-red-700">{error}</p>}
    {current&&<div className="mt-4 min-w-0 rounded-xl border bg-white p-4"><h3 className="font-semibold">Broker Portfolio snapshot</h3><p className="mt-1 text-xs text-stone-500">Provider facts as of {new Date(current.synced_at).toLocaleString()}. This account is shown separately from the manual ledger below. Historical records do not add to holdings. Amounts retain their reported currencies.</p>
      <div className="my-3 flex flex-wrap gap-3"><label className="text-xs">Broker account<select className="input mt-1" value={account} onChange={e=>change(()=>{setAccount(e.target.value);setOffset(0);})}>{accounts.map(a=><option key={a.account_key} value={a.account_key}>{a.label}</option>)}</select></label><label className="text-xs">Records<select className="input mt-1" value={kind} onChange={e=>change(()=>{setKind(e.target.value);setOffset(0);})}>{[['position','Positions'],['orders','Orders / fills'],['dividends','Dividends'],['transactions','Cash transactions']].map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label></div>
      <div className="grid gap-3 sm:grid-cols-3">{[['Account value',s.totalValue],['Investments',s.investments?.currentValue],['Available cash',s.cash?.availableToTrade]].map(([label,value])=><div key={label} className="rounded bg-stone-50 p-3"><p className="text-xs">{label}</p><strong>{moneyCurrency(value,currency)}</strong></div>)}</div>
      {selected&&<div className="my-4 rounded border p-3"><h4 className="font-medium">Notes and tags · record {selected.id}</h4><label className="block text-sm">Note<textarea className="input" value={note} onChange={e=>setNote(e.target.value)}/></label><label className="block text-sm">Tags (comma separated)<input className="input" value={tags} onChange={e=>setTags(e.target.value)}/></label><button className="mini-btn mt-2" onClick={save}>Save Portfolio review</button></div>}
      {loading?<p className="py-4">Loading broker records…</p>:<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Instrument / type','Date','Quantity','Price','Reported value','Provider ID','Review'].map(v=><th key={v} className="whitespace-nowrap p-2">{v}</th>)}</tr></thead><tbody>{data.items.map(r=>{const f=r.facts,o=f.order||{},fill=f.fill||{},inst=f.instrument||o.instrument||{},wallet=f.walletImpact||fill.walletImpact||{};return <tr key={r.id} className="border-t"><td className="p-2">{inst.ticker||f.ticker||o.ticker||f.type}{!r.active&&' (closed snapshot)'}</td><td className="whitespace-nowrap p-2">{fill.filledAt||f.paidOn||f.dateTime||f.createdAt||o.createdAt||'Unavailable'}</td><td className="p-2">{f.quantity??fill.quantity??o.quantity??'—'}</td><td className="p-2">{moneyCurrency(f.currentPrice??fill.price,inst.currency||o.currency)}</td><td className="whitespace-nowrap p-2">{moneyCurrency(f.amount??wallet.currentValue??wallet.netValue,f.currency||wallet.currency)}</td><td className="p-2">{r.external_id}</td><td className="p-2"><button className="text-blue-700" onClick={()=>change(()=>{setSelected(r);setNote(r.note);setTags(r.tags.join(', '));})}>Notes / tags</button><details><summary className="cursor-pointer text-xs">Execution facts</summary><pre className="max-w-md whitespace-pre-wrap break-all text-xs">{JSON.stringify(f,null,2)}</pre></details>{r.note&&<p className="max-w-xs whitespace-pre-wrap break-words text-xs">{r.note}</p>}</td></tr>;})}</tbody></table></div>}
      <div className="mt-3 flex gap-3 text-xs"><button disabled={loading||!offset} onClick={()=>setOffset(v=>Math.max(0,v-100))}>Previous</button><span>{data.total} records</span><button disabled={loading||offset+100>=data.total} onClick={()=>setOffset(v=>v+100)}>Next</button></div>
    </div>}
  </section>;
}
