import test from 'node:test';
import assert from 'node:assert/strict';
import {navigationState,navigationKey,exportScope,detailWindow,tradeReference,researchRow} from '../src/features/strategy-lab/reviewNavigation.js';
import {ResearchPdf,evidenceLines} from '../src/features/strategy-lab/researchPdf.js';
import {toCsv} from '../src/utils/csv.js';
const trades=Array.from({length:103},(_,i)=>({symbol:'SPY',entry_time:new Date(Date.UTC(2026,0,1,0,i)).toISOString(),exit_time:new Date(Date.UTC(2026,0,1,0,i+2)).toISOString(),net_pnl:i-50,r_multiple:i/100,metadata:{}}));
test('navigation follows filtered and sorted order with disabled boundaries',()=>{const list=[trades[12],trades[3],trades[8]];assert.equal(navigationState(list,list[0]).previous,null);assert.equal(navigationState(list,list[0]).next,list[1]);assert.equal(navigationState(list,list[2]).next,null);assert.equal(navigationState(list,trades[0]).index,-1);assert.equal(navigationState(list,list[1]).count,3);});
test('keyboard ignores editable targets, modifiers and repeat',()=>{assert.equal(navigationKey({key:'K'}),'next');assert.equal(navigationKey({key:'j'}),'previous');for(const event of [{ctrlKey:true},{repeat:true},{target:{closest:()=>true}}])assert.equal(navigationKey({key:'k',...event}),null);assert.equal(navigationKey({key:'ArrowLeft'}),null);});
test('all, filtered and selected exports retain immutable snapshot IDs',()=>{const filtered=[trades[8],trades[2]];assert.equal(exportScope(trades,filtered,new Set([7]),'all').length,103);assert.deepEqual(exportScope(trades,filtered,new Set([7]),'filtered').map(x=>x.index),[8,2]);assert.deepEqual(exportScope(trades,filtered,new Set([7]),'selected').map(x=>x.index),[7]);assert.equal(tradeReference(175,41),'Run 175 / Trade 42');});
test('entry and exit detail use session bars, bounded by available history',()=>{const bars=trades.map(t=>({timestamp:t.entry_time}));assert.deepEqual(detailWindow(bars,trades[50].entry_time,40,25),{from:10,to:75});assert.deepEqual(detailWindow(bars,trades[50].entry_time,15,20),{from:35,to:70});assert.deepEqual(detailWindow(bars,trades[0].entry_time,40,25),{from:0,to:25});assert.equal(detailWindow([],trades[0].entry_time,40,25),null);});
test('CSV rows match selection, preserve evidence provenance and missing data',()=>{const rows=exportScope(trades,[trades[8],trades[2]],new Set(),'filtered').map(({trade,index})=>researchRow({saved_run:{id:175}},trade,index,{evidence:{entry:[{label:'EMA',value:42,provenance:'reconstructed'}]}}));assert.equal(rows.length,2);assert.equal(rows[0].trade_number,9);assert.equal(rows[0]['entry.0.EMA.provenance'],'reconstructed');assert.equal(rows[0].duration_minutes,2);assert.equal(rows[0].pnl_pct,null);assert.equal(toCsv(rows).split('\r\n').length,3);});
test('evidence retains generic indicators and recorded / missing distinctions',()=>{const lines=evidenceLines({series:[{label:'Donchian',timeframe:'1d'}],evidence:{entry:[{label:'ATR',value:null,provenance:'recorded'}]},warnings:['Unavailable']});assert.match(lines.join(' '),/Not recorded/);assert.match(lines.join(' '),/Donchian/);assert.match(lines.join(' '),/reconstructed/);});
for(const count of [1,103])test(`PDF writes ${count} trades with valid cross references and selectable identifiers`,async()=>{const pdf=new ResearchPdf();for(let i=0;i<count;i++)pdf.page(tradeReference(175,i),['Selectable evidence (safe) \\ path','Strategy evidence']);const data=await pdf.blob().text();assert.match(data,/%PDF-1.4/);assert.match(data,new RegExp('/Count '+count+' '));assert.match(data,new RegExp('Trade '+count));const offset=Number(data.match(/startxref\n(\d+)/)[1]);assert.equal(data.slice(offset,offset+4),'xref');for(const [i,line] of data.slice(offset).split('\n').slice(3,3+3+count*2).entries()){const pos=Number(line.slice(0,10));assert.equal(data.slice(pos,pos+`${i+1} 0 obj`.length),`${i+1} 0 obj`);}});
test('long evidence automatically continues without dropping fields',()=>{const pdf=new ResearchPdf();pdf.page('Trade 1',Array.from({length:100},(_,i)=>'Evidence '+i));assert.equal(pdf.pages.length,4);assert.equal(pdf.pages.flatMap(p=>p.lines).length,100);});

test('CSV preserves recorded signal times and notional return without inference',()=>{const row=researchRow({saved_run:{id:5}},{...trades[0],pnl_pct:-.18,metadata:{review_entry:{signal_time:'2026-01-01T00:00:00Z'},review_exit:{signal_time:'2026-01-01T00:01:00Z'}}},0);assert.equal(row.entry_signal_time,'2026-01-01T00:00:00Z');assert.equal(row.exit_signal_time,'2026-01-01T00:01:00Z');assert.equal(row.pnl_bps,-18);});
test('PDF preserves non-ASCII values as explicit escapes and bounds long titles',async()=>{const pdf=new ResearchPdf();pdf.page('A'.repeat(200),['\u03b1']);assert.ok(pdf.pages[0].title.length<=84);const text=await pdf.blob().text();assert.ok(text.includes('03b1'));assert.ok(pdf.pages[0].lines.join('').includes('A'.repeat(200)));});
