import test from 'node:test';
import assert from 'node:assert/strict';
import {reviewPriceDomain,validCandle} from '../src/features/strategy-lab/reviewScale.js';
const candle=(low,high,time=0)=>({low,high,open:low,close:high,time});
test('distant evidence cannot flatten candles; local VWAP bands and all wicks fit',()=>{const result=reviewPriceDomain([candle(737,739)],[{label:'Daily regime',value:709},{label:'VWAP lower',value:736.2},{label:'VWAP upper',value:739.8},{label:'Wide target',value:900}]);assert.ok(result.priceRange.minValue<736.2);assert.ok(result.priceRange.minValue>735);assert.ok(result.priceRange.maxValue>739.8);assert.ok(result.priceRange.maxValue<741);assert.equal(result.offScale.length,2);assert.ok(result.padding>0);});
test('nearby context remains visible without clipping candles',()=>{const d=reviewPriceDomain([candle(714,716)],[{label:'Context',value:713}]);assert.ok(d.priceRange.minValue<713);assert.ok(d.priceRange.maxValue>716);assert.equal(d.offScale.length,0);});
test('scale uses current visible range and does not chain expansions',()=>{const bars=[candle(100,102,0),candle(737,739,1),candle(737,739,2)];const d=reviewPriceDomain(bars,[{label:'Near',value:736},{label:'Distant',value:735}],{from:1,to:2});assert.ok(d.priceRange.minValue>735);assert.ok(d.offScale[0].includes('Distant'));});
test('flat, tiny and missing windows are safe; legitimate extreme wicks remain',()=>{for(const price of [0,.00001,738]){const d=reviewPriceDomain([candle(price,price)]);assert.ok(d.priceRange.minValue<price);assert.ok(d.priceRange.maxValue>price);}assert.equal(reviewPriceDomain([]),null);assert.equal(validCandle({...candle(1,2),low:null}),false);assert.equal(validCandle({...candle(1,2),high:NaN}),false);const d=reviewPriceDomain([candle(737,739),candle(1,1000)]);assert.ok(d.priceRange.minValue<1);assert.ok(d.priceRange.maxValue>1000);});
test('generic dynamic overlay ranges report off-scale evidence and retain near points',()=>{const bars=[candle(10,12,1),candle(11,13,2)];const d=reviewPriceDomain(bars,[{label:'Channel',points:[{time:0,value:999},{time:1,value:1},{time:2,value:14}]}]);assert.ok(d.priceRange.maxValue>14);assert.ok(d.offScale[0].includes('1.000000'));assert.ok(!d.offScale.join().includes('999'));});
