import {useEffect,useMemo,useState} from 'react';
import {useUIPreference} from '../../app/useUIPreference.js';
import {useWatchlist} from '../../app/watchlist.js';
import {api} from '../../api/client.js';
import DataTable from '../../components/table/DataTable.jsx';
import WatchlistBar from '../../components/WatchlistBar';
import {Section} from '../../components/ui.jsx';
import {scanFields,blankScan,saveScan} from './scanModel.js';
import {useScan} from './useScan.js';
export default function ScreenerPage({onOpenTicker,onWorkflow}) {
 const watch=useWatchlist(),[query,setQuery]=useUIPreference('screener.query',blankScan()),[scans,setScans]=useUIPreference('screener.scans',[]),[name,setName]=useState(''),[selected,setSelected]=useState('');
 const {result,loading,error,setError,run,refresh,job}=useScan();
 useEffect(()=>{run(query);},[]);
 const patch=(i,change)=>setQuery(q=>({...q,conditions:q.conditions.map((c,n)=>n===i?{...c,...change}:c)}));
 const defaults=new Set(['price','return_20d','return_60d','relative_volume','atr_pct','trend_aligned','distance_52w_high','market_cap','volume','pe_ratio']);
 const columns=useMemo(()=>[{key:'ticker',label:'Ticker',kind:'text',sticky:true},{key:'name',label:'Company',kind:'text'},...scanFields.map(([key,label])=>({key,label,kind:'number',hidden:!defaults.has(key),render:r=>r[key]==null?'Unavailable':new Intl.NumberFormat('en-GB',{maximumFractionDigits:2}).format(r[key])})),{key:'snapshot_at',label:'Daily snapshot',kind:'date'},{key:'snapshot_stale',label:'Freshness',kind:'category',value:r=>r.snapshot_stale?'Stale / missing':'Within 72h'}],[]);
 const act=(target,row)=>onWorkflow?onWorkflow(target,{symbol:row.ticker,timeframe:'1d'}):onOpenTicker(row.ticker);
 const persist=(rename=false)=>{try{const next=saveScan(scans,name,query);setScans(rename&&selected&&selected!==name?next.filter(s=>s.name!==selected):next);setSelected(name.trim());}catch(e){setError(e.message);}};
 return <div className="dense-page space-y-5"><div><p className="eyebrow">Discover</p><h2 className="text-3xl font-semibold">Screener</h2><p className="muted text-sm mt-2">Scan the locally cached US universe. Technical snapshots use completed daily bars; fundamentals and prices retain their own timestamps.</p></div><WatchlistBar onSelect={onOpenTicker} compact/>
 <section className="insight-panel"><div className="ui-toolbar"><select aria-label="Saved scan" className="input table-density" value={selected} onChange={e=>{const scan=scans.find(s=>s.name===e.target.value);setSelected(e.target.value);if(scan){setName(scan.name);setQuery(structuredClone(scan.query));}}}><option value="">Saved scans</option>{scans.map(s=><option key={s.name}>{s.name}</option>)}</select><input aria-label="Scan name" className="input table-search" placeholder="Name this scan" value={name} onChange={e=>setName(e.target.value)}/><button className="mini-btn" onClick={()=>persist()}>Save</button><button className="mini-btn" disabled={!selected} onClick={()=>persist(true)}>Rename</button><button className="mini-btn" disabled={!selected} onClick={()=>{const copy=selected+' copy';setScans(saveScan(scans,copy,query));setSelected(copy);setName(copy);}}>Duplicate</button><button className="mini-btn" disabled={!selected} onClick={()=>{setScans(scans.filter(s=>s.name!==selected));setSelected('');setName('');}}>Delete scan</button><button className="mini-btn" onClick={()=>{const empty=blankScan();setQuery(empty);setSelected('');setName('');run(empty);}}>Reset scan</button></div>
 <div className="ui-toolbar mt-4"><label>Match <select aria-label="Match conditions" className="input table-density" value={query.match} onChange={e=>setQuery({...query,match:e.target.value})}><option value="all">ALL conditions</option><option value="any">ANY condition</option></select></label><label>Universe <select className="input table-density" value={query.security_type} onChange={e=>setQuery({...query,security_type:e.target.value})}>{['stock','etf','adr','reit','spac','preferred','unit','warrant','right','fund','all'].map(t=><option key={t}>{t}</option>)}</select></label><input aria-label="Ticker or company" className="input table-search" placeholder="Ticker or company" value={query.text} onChange={e=>setQuery({...query,text:e.target.value})}/></div>
 <details className="mt-3"><summary className="text-sm cursor-pointer">Universe options</summary><div className="ui-toolbar mt-2"><input aria-label="Exchange" placeholder="Exchange (e.g. NASDAQ)" className="input table-search" value={query.exchange||''} onChange={e=>setQuery({...query,exchange:e.target.value})}/>{['tradable','fractionable','shortable'].map(key=><label key={key}>{key}<select className="input table-density" value={query[key]==null?'any':String(query[key])} onChange={e=>setQuery({...query,[key]:e.target.value==='any'?null:e.target.value==='true'})}><option value="any">Any</option><option value="true">Yes</option><option value="false">No</option></select></label>)}<label><input type="checkbox" checked={Boolean(query.require_fundamentals)} onChange={e=>setQuery({...query,require_fundamentals:e.target.checked})}/> Require fundamentals</label></div></details>
 {query.conditions.map((c,i)=><div key={i} className="ui-toolbar mt-2"><select aria-label={`Condition ${i+1} field`} className="input table-density" value={c.field} onChange={e=>patch(i,{field:e.target.value})}>{scanFields.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><select aria-label={`Condition ${i+1} operator`} className="input table-density" value={c.operator} onChange={e=>patch(i,{operator:e.target.value})}>{['>','<','>=','<=','=','!='].map(op=><option key={op}>{op}</option>)}</select><select aria-label={`Condition ${i+1} comparison`} className="input table-density" value={c.other_field||''} onChange={e=>patch(i,{other_field:e.target.value})}><option value="">Number</option>{scanFields.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select>{!c.other_field&&<input aria-label={`Condition ${i+1} value`} className="input table-density" value={c.value} placeholder="10 or 2B" onChange={e=>patch(i,{value:e.target.value})}/>}<button aria-label={`Remove condition ${i+1}`} className="mini-btn" onClick={()=>setQuery({...query,conditions:query.conditions.filter((_,n)=>n!==i)})}>Remove</button></div>)}
 <div className="ui-toolbar mt-4"><button className="mini-btn" disabled={query.conditions.length>=30} onClick={()=>setQuery({...query,conditions:[...query.conditions,{field:'price',operator:'>',value:'10'}]})}>+ Add condition</button><button className="mini-btn ledger-primary text-white" disabled={loading} onClick={()=>run(query)}>{loading?'Applying...':'Apply filters'}</button></div><p className="muted text-xs mt-2">Missing values never pass a comparison. % fields use percentage points (5 means 5%); fundamental ratios use decimals (0.2 means 20%). No ranking or trade recommendation.</p></section>
 {error&&<div role="alert" className="text-sm negative">{error} <button className="mini-btn" onClick={()=>run(query)}>Retry scan</button></div>}
 <p role="status" className="muted text-xs">{result.total} matches · technical coverage {result.coverage.available||0}/{result.coverage.universe||0}. Cached results stay visible while maintenance runs{['queued','running'].includes(job?.status)?` (${job.phase||'updating'} ${job.processed||0}/${job.total||0})`:''}. Latest technical snapshot: {result.coverage.latest||'unavailable'}. Current-universe only: historical universe may contain survivorship bias.</p>
 <Section id="screener-data" title="Data maintenance"><p className="muted text-xs">Ledger serves the last persistent snapshot immediately. On backend startup it refreshes technicals from local daily history and, when Alpaca is configured and stale, refreshes batched prices in the background. Existing rows are never blanked while that work runs. SEC fundamentals remain manual because the bulk archive is large.</p><div className="ui-toolbar mt-2"><button className="mini-btn" disabled={['running','queued'].includes(job?.status)} onClick={refresh}>Refresh technical cache now</button><button className="mini-btn" onClick={()=>api.refreshScreenerPrices().then(()=>run(query,{quiet:true})).catch(e=>setError(e.message))}>Refresh prices now</button><button className="mini-btn" onClick={()=>api.refreshScreenerFundamentals().then(()=>run(query,{quiet:true})).catch(e=>setError(e.message))}>Refresh SEC fundamentals</button></div><p className="muted text-xs mt-2">Maintenance: {job?.status||'idle'}{job?.phase&&job.phase!=='idle'?` · ${job.phase}`:''}; technicals {job?.processed||0}/{job?.total||0}, stored {job?.stored||0}, failed {job?.failed||0}{job?.price_stored?` · prices stored ${job.price_stored}`:''}. Load daily history in Charts/Backtest to extend technical coverage.</p></Section>
 <DataTable id="screener" label="Screener results" rows={result.items} columns={columns} primaryAction={{label:'Chart',onClick:r=>act('Charts',r)}} actions={r=>[{label:'Research',onClick:()=>act('Research',r)},{label:'Replay',onClick:()=>act('Replay',r)},{label:'Backtest',onClick:()=>act('Backtest',r)},{label:watch.has(r.ticker)?'Remove Watchlist':'Add Watchlist',onClick:()=>watch.toggle(r.ticker)}]} summary={rows=><p className="muted text-xs px-3 pb-3">N = {rows.length} visible matches. Discovery snapshots are not a historical portfolio result.</p>}/>
 </div>;
}
