import {useEffect,useRef,useState} from 'react';
import {api} from '../../api/client';
import PriceChart from '../research/PriceChart.jsx';
const ACK='Audit this concept on verified development data; follow-up metrics are research only';
const format=n=>n==null?'Unavailable':Number(n).toFixed(2);
export default function ConceptAudits({concepts}){
 const [projects,setProjects]=useState([]),[project,setProject]=useState(''),[concept,setConcept]=useState(''),[timeframe,setTimeframe]=useState('1m'),[params,setParams]=useState('{}'),[horizon,setHorizon]=useState(20);
 const [items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[consent,setConsent]=useState(false),[example,setExample]=useState(null);
 const pending=useRef(null);
 useEffect(()=>{let alive=true;api.researchProjects().then(r=>{if(alive)setProjects(r.items);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[]);
 useEffect(()=>{setItems([]);setExample(null);if(!project)return;let alive=true,timer;const poll=async()=>{try{const r=await api.conceptAudits(project);if(!alive)return;setItems(r.items);if(r.items.some(x=>x.status==='RUNNING'))timer=setTimeout(poll,2000);}catch(e){if(alive)setError(e.message);}};poll();return()=>{alive=false;clearTimeout(timer);};},[project,busy]);
 const submit=async()=>{setBusy(true);setError('');try{const parsed=JSON.parse(params);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw Error('Concept parameters must be a JSON object.');const request={concept:{key:concept,timeframe,params:parsed},horizon_bars:Number(horizon),acknowledgement:ACK};const signature=JSON.stringify([project,request]);if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};await api.researchProjectAction(project,'concept-audits',{...request,request_key:pending.current.key});setConsent(false);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const edit=(setter,value)=>{setter(value);setConsent(false);};
 return <article className="insight-panel"><h4 className="font-semibold">Detector benchmarks and visual audit</h4><p className="text-sm muted mt-2">Independent concept research, not strategy performance. Uses a verified development baseline and its already prepared timeframe; maximum 2,000 bars and 12 audit attempts per project. Later price behavior is diagnostic only. Prefix checks do not prove correctness for every possible input or promote a detector to Stable.</p>{error&&<p role="alert">{error}</p>}<div className="grid gap-3 mt-3 md:grid-cols-2"><label>Development project<select className="input" value={project} onChange={e=>edit(setProject,e.target.value)}><option value="">Choose a verified baseline project</option>{projects.filter(p=>p.state==='BASELINE_ANALYSIS'&&p.baseline_run_id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Exact concept version<select className="input" value={concept} onChange={e=>edit(setConcept,e.target.value)}><option value="">Choose a detector</option>{concepts.map(c=><option key={c.key} value={c.key}>{c.key}</option>)}</select></label><label>Prepared timeframe<select className="input" value={timeframe} onChange={e=>edit(setTimeframe,e.target.value)}>{['1m','5m','15m','30m','1h','4h','1d'].map(tf=><option key={tf}>{tf}</option>)}</select></label><label>Follow-up horizon (bars)<input className="input" type="number" min={1} max={100} value={horizon} onChange={e=>edit(setHorizon,e.target.value)}/></label></div><label className="block mt-2">Concept parameters (JSON object)<textarea className="input" value={params} onChange={e=>edit(setParams,e.target.value)}/></label><label className="block text-sm mt-2"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Audit verified development data; follow-up outcomes are research only.</label><button className="mini-btn mt-2" disabled={busy||!project||!concept||!consent||items.some(x=>x.status==='RUNNING')} onClick={submit}>{busy?'Auditing concept...':'Run concept audit'}</button><p className="text-xs muted mt-2">Attempts used: {items.length} / 12. Failed/interrupted attempts remain recorded. Identical submissions reuse their request key.</p>
 {items.map(a=><details key={a.id} className="mt-3"><summary>{a.request.concept.key} / {a.status}{a.report?` / N ${a.report.observation_count} / prefix checks ${a.report.causality.status}`:''}</summary>{a.error&&<p role="alert">{a.error}</p>}{a.report&&<><p className="text-xs muted mt-2">{a.report.bar_count} bars / confirmation lag median {format(a.report.confirmation_lag_seconds.median)} seconds / zone size median {format(a.report.zone_size_midpoint_bps.median)} bps</p><p className="text-sm mt-2">Follow-up: {a.report.followup.complete_observations} complete / {a.report.followup.right_censored_observations} right-censored. Upward {format(a.report.followup.upward_bps.mean)} bps / downward {format(a.report.followup.downward_bps.mean)} bps. These are price excursions, not trade returns.</p><p className="text-xs mt-2">Touched zones with complete horizons: {a.report.followup.touched_complete_zones} / {a.report.followup.complete_zones}. {a.report.sample_policy}</p><div className="ui-toolbar mt-2">{a.report.examples.map(x=><button className="mini-btn" key={x.index} onClick={()=>setExample({report:a.report,example:x})}>Inspect {x.observation.label} #{x.index+1}</button>)}</div><details className="mt-2"><summary>Definitions, counts, prefix checks and limitations</summary><pre className="text-xs max-h-96 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify({...a.report,examples:undefined},null,2)}</pre></details></>}</details>)}
 {example&&<section className="mt-4"><div className="ui-toolbar"><h5 className="font-semibold">Concept example: {example.example.observation.label}</h5><button className="mini-btn" onClick={()=>setExample(null)}>Close concept example</button></div><p className="text-xs mt-2">Occurred {example.example.observation.occurred_at} / known at {example.example.observation.confirmed_at}. Bars after confirmation are shown for retrospective diagnostics only. Frozen reference levels start at confirmation; series use their recorded confirmation timestamps.</p><PriceChart bars={example.example.bars} overlays={example.example.overlays} timeframe={example.report.timeframe} height={360} showVolume={false}/><pre className="text-xs overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(example.example.followup,null,2)}</pre></section>}
 </article>;
}
