import {money} from "./replayHelpers.js";
export default function ReplayOrderTicket({orderType,setOrderType,dataset,contracts,positionAmount,setContracts,setPositionAmount,entryPrice,setEntryPrice,stop,setStop,target,setTarget,setup,setSetup,position,pendingOrder,nextBar,atFrontier,placeOrder,setPendingOrder,currentBar,metrics,setPendingClose,pendingClose,closedTrade,journalStatus}){return <div className="rounded-lg border border-stone-200 p-4"><h4 className="text-sm font-semibold">Order ticket</h4><p className="mt-1 text-[11px] text-stone-500">Risk, planned R:R and realised R are calculated from the actual fill, stop, target and exit; they are not manual inputs.</p>
            <div className="mt-3 grid grid-cols-2 gap-3"><Field label="Order type"><select className="input" value={orderType} onChange={(e) => setOrderType(e.target.value)}><option value="market">Market · next bar open</option><option value="limit">Limit · at price</option><option value="stop">Stop entry · at price</option></select></Field><Field label={dataset?.instrument?.asset_type === "future" ? "Contracts" : "Position value · USD"}><input type="number" className="input" value={dataset?.instrument?.asset_type === "future" ? contracts : positionAmount} onChange={(e) => dataset?.instrument?.asset_type === "future" ? setContracts(e.target.value) : setPositionAmount(e.target.value)} /></Field>
              {orderType !== "market" && <Field label="Entry price"><input type="number" step="any" className="input" value={entryPrice} onChange={(e) => setEntryPrice(e.target.value)} placeholder="Price" /></Field>}
              <Field label="Stop loss"><input type="number" step="any" className="input" value={stop} onChange={(e) => setStop(e.target.value)} /></Field><Field label="Take profit"><input type="number" step="any" className="input" value={target} onChange={(e) => setTarget(e.target.value)} /></Field><Field label="Setup"><input className="input" value={setup} onChange={(e) => setSetup(e.target.value)} placeholder="Optional" /></Field></div>
            {!position && !pendingOrder && <div className="mt-3 grid grid-cols-2 gap-2"><button data-replay-buy disabled={!nextBar || !atFrontier} onClick={() => placeOrder("long")} className="rounded-md bg-emerald-700 px-3 py-2 text-xs font-medium text-white disabled:opacity-40">BUY / LONG</button><button data-replay-sell disabled={!nextBar || !atFrontier} onClick={() => placeOrder("short")} className="rounded-md bg-red-700 px-3 py-2 text-xs font-medium text-white disabled:opacity-40">SELL / SHORT</button></div>}
            {pendingOrder && <div className="mt-3 rounded bg-amber-50 p-3 text-xs text-amber-900"><strong>{pendingOrder.direction.toUpperCase()} {pendingOrder.order_type.toUpperCase()}</strong>{pendingOrder.entry_price != null ? ` @ ${money(pendingOrder.entry_price)}` : " · next bar open"}. Stop {money(pendingOrder.stop_loss)} · target {money(pendingOrder.take_profit)}. <button onClick={() => setPendingOrder(null)} className="ml-2 underline">Cancel order</button></div>}
            {dataset?.instrument?.asset_type === "future" && <p className="mt-2 text-xs text-amber-700">Raw execution: {currentBar?.source_contract || 'unavailable'} · USD {dataset.instrument.point_value} per point per contract; tick {dataset.instrument.tick_size}. {currentBar?.roll_schedule_version}. Open positions cannot cross rolls.</p>}
            {position && <div className="mt-3 rounded bg-blue-50 p-3 text-xs text-blue-900"><div><strong>{position.direction.toUpperCase()}</strong> · entry {money(position.entry_price)} · qty {position.quantity.toFixed(4)}</div><div className="mt-1">Stop {money(position.stop_loss)} · target {money(position.take_profit)}</div><div className="mt-1">Initial risk <strong>{money(metrics.risk)}</strong> · Planned R:R <strong>{metrics.rr == null ? "—" : `${metrics.rr.toFixed(2)}:1`}</strong> · MFE/share {money(position.mfe_per_share)} · MAE/share {money(position.mae_per_share)}</div><button disabled={!nextBar} onClick={() => setPendingClose(true)} className="mt-2 underline">{pendingClose ? "Manual close queued for next bar open" : "Close manually on next bar open"}</button></div>}
            {closedTrade && <div className={`mt-3 rounded p-3 text-xs ${closedTrade.net_pnl >= 0 ? "bg-emerald-50 text-emerald-900" : "bg-red-50 text-red-900"}`}><strong>Closed:</strong> {closedTrade.exit_reason} · {money(closedTrade.exit_price)} · P&L {money(closedTrade.net_pnl)}</div>}
            {journalStatus && <p className="mt-2 text-xs text-stone-600">{journalStatus}</p>}
          </div>;}
function Field({label,children}){return <label className="block"><span className="mb-1 block text-xs muted">{label}</span>{children}</label>;}
