import {useEffect,useState} from 'react';
import ConceptAudits from './ConceptAudits.jsx';
import ResearchCandidates from './ResearchCandidates.jsx';
import ResearchLoop from './ResearchLoop.jsx';
import ResearchTrials from './ResearchTrials.jsx';
import ResearchCommittee from './ResearchCommittee.jsx';
import ResearchEvidence from './ResearchEvidence.jsx';
import ResearchHypotheses from './ResearchHypotheses.jsx';
import {api} from '../../api/client';
const WARNING='Using this dataset means it will no longer be considered unseen.';
export default function ResearchFoundations({mode,strategies,runs,configuration}){
 const [hypothesisRevision,setHypothesisRevision]=useState(0);
 const [trialRevision,setTrialRevision]=useState(0);
 const [items,setItems]=useState([]),[project,setProject]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[run,setRun]=useState('');
 const [form,setForm]=useState({name:'',strategy_key:configuration?.strategy_key||strategies[0]?.key||'',symbol:'NQ1!',timeframe:'1m',start:'',end:'',holdoutStart:'',holdoutEnd:'',maxHypotheses:12,maxVariants:9,maxTotal:60,maxLlmCalls:12,maxTrialRuns:80,maxTrialMinutes:60,maxSpend:10});
 useEffect(()=>{if(!project||!['BASELINE_PENDING','BASELINE_RUNNING'].includes(project.state))return;const timer=setInterval(()=>api.researchProject(project.id).then(setProject).catch(e=>setError(e.message)),2500);return()=>clearInterval(timer);},[project?.id,project?.state]);
 const field=(key,value)=>setForm(f=>({...f,[key]:value}));
 const refresh=()=> (mode==='Market Concepts'?api.marketConcepts():api.researchProjects()).then(r=>setItems(r.items));
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[mode]);
 const act=async fn=>{setBusy(true);setError('');try{setProject(await fn());await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const create=()=>act(()=>{const base={symbols:[form.symbol.toUpperCase()],timeframe:form.timeframe};const datasets=[{...base,start:form.start,end:form.end,state:'DEVELOPMENT'}];if(form.holdoutStart||form.holdoutEnd)datasets.push({...base,start:form.holdoutStart,end:form.holdoutEnd,state:'LOCKED_HOLDOUT'});return api.createResearchProject({research_budget:{max_llm_spend_usd:Number(form.maxSpend),max_trial_runs:Number(form.maxTrialRuns),max_trial_minutes:Number(form.maxTrialMinutes),max_llm_calls:Number(form.maxLlmCalls),max_hypotheses:Number(form.maxHypotheses),max_variants_per_hypothesis:Number(form.maxVariants),max_total_variants:Number(form.maxTotal)},name:form.name,strategy_key:form.strategy_key,datasets});});
 if(mode==='Market Concepts')return <section className="mt-5 space-y-3"><h3 className="text-xl font-semibold">Versioned Market Concepts</h3><p className="muted text-sm">Detection definitions, separate from trading decisions. Experimental does not mean profitable. Existing strategies retain their local definitions until parity-tested migration.</p>{error&&<p role="alert">{error}</p>}<ConceptAudits concepts={items}/>{items.map(c=><article className="insight-panel" key={c.key}><h4 className="font-semibold">{c.key}</h4><p className="text-xs muted">{c.scope} / {c.status}</p><p className="mt-2 text-sm">{c.description}</p><p className="mt-2 text-xs">{c.limitations}</p><p className="text-xs mt-2">Declared consumers: {c.used_by.join(', ')||'None yet; no inferred equivalence'}</p><details className="mt-2 text-xs"><summary>Parameters, dependencies and implementation hash</summary><pre className="overflow-auto whitespace-pre-wrap break-all">{JSON.stringify({parameters:c.parameter_schema,dependencies:c.dependencies,source_sha:c.source_sha},null,2)}</pre></details></article>)}</section>;
 return <section className="mt-5 space-y-4"><h3 className="text-xl font-semibold">Research Agent / deterministic foundation</h3><p className="muted text-sm">Create a durable project, queue its frozen baseline, and inspect saved engine results. The optional read-only committee can review development evidence when explicitly requested. Explicitly approved development cells run through the backend queue. A separate opt-in bounded loop can authorize subsequent development experiments. Generated code remains disabled. No orders are placed.</p>
 {error&&<p role="alert" className="text-red-700">{error}</p>}
 <details className="insight-panel" open={!items.length}><summary>Create research project</summary><div className="grid gap-3 mt-3 sm:grid-cols-2 lg:grid-cols-3">
 <label>Project name<input className="input" value={form.name} onChange={e=>field('name',e.target.value)}/></label>
 <label>Strategy<select className="input" value={form.strategy_key} onChange={e=>field('strategy_key',e.target.value)}>{strategies.map(s=><option key={s.key} value={s.key}>{s.name}</option>)}</select></label>
 <label>Symbol<input className="input" value={form.symbol} onChange={e=>field('symbol',e.target.value)}/></label>
 <label>Timeframe<select className="input" value={form.timeframe} onChange={e=>field('timeframe',e.target.value)}>{['1m','5m','15m','30m','1h','4h','1d'].map(tf=><option key={tf}>{tf}</option>)}</select></label>
 {[['start','Development from'],['end','Development through'],['holdoutStart','Locked holdout from (optional)'],['holdoutEnd','Locked holdout through']].map(([key,label])=><label key={key}>{label}<input type="date" className="input" value={form[key]} onChange={e=>field(key,e.target.value)}/></label>)}</div><details className="mt-3"><summary>Preregistration budget</summary><div className="grid gap-3 sm:grid-cols-3">{[["maxSpend","Model reservation budget (USD)"],["maxHypotheses","Maximum hypotheses"],["maxVariants","Variants per hypothesis"],["maxTotal","Total registered variants"],["maxLlmCalls","Maximum model calls (0 disables)"],["maxTrialRuns","Maximum trial simulations"],["maxTrialMinutes","Active minutes per trial"]].map(([key,label])=><label key={key}>{label}<input className="input" type="number" min={key==="maxLlmCalls"?0:1} value={form[key]} onChange={e=>field(key,e.target.value)}/></label>)}</div><p className="text-xs muted">Fixed at project creation; variant bounds limit registration; model calls have their own cap. A USD budget requires backend model prices. Reservations conservatively charge the maximum request/output allowance; they are not a provider invoice.</p></details><button className="mini-btn mt-3" disabled={busy} onClick={create}>Create project</button></details>
 <div className="ui-toolbar">{items.map(p=><button className="mini-btn" disabled={busy} key={p.id} onClick={()=>act(()=>api.researchProject(p.id))}>{p.name} / {p.state}</button>)}</div>
 {project&&<><article className="insight-panel"><h4 className="font-semibold">{project.name} / {project.state}</h4><p className="text-xs muted">User-directed research / {project.research_debt.uses} recorded inspections / heuristic research debt</p>{project.last_error&&<p role="alert" className="text-sm mt-2">{project.last_error}</p>}
 {['CREATED','BASELINE_PENDING'].includes(project.state)&&<div className="mt-3"><p className="text-xs muted">Baseline uses the current Backtest configuration (strategy, symbols, dates, sizing and costs). Declare sufficient development history for required warmup. The payload is frozen on first submission.</p><button className="mini-btn mt-2" disabled={busy||(!project.baseline_payload&&configuration?.strategy_key!==project.strategy_key)} onClick={()=>act(()=>api.researchProjectAction(project.id,'baseline',project.baseline_payload||configuration))}>Queue frozen baseline</button></div>}
 <div className="ui-toolbar mt-3"><select aria-label="Saved run to inspect" className="input" value={run} onChange={e=>setRun(e.target.value)}><option value="">Select a saved engine run</option>{runs.filter(r=>r.strategy_key===project.strategy_key).map(r=><option key={r.id} value={r.id}>{r.name||'Run '+r.id} / {r.start_date} - {r.end_date}</option>)}</select><button className="mini-btn" disabled={busy||!run||['PAUSED','ARCHIVED'].includes(project.state)} onClick={()=>act(()=>api.researchProjectAction(project.id,'inspect',{run_id:Number(run)}))}>Inspect / compare with baseline</button>{project.state!=='ARCHIVED'&&<><button className="mini-btn" disabled={busy} onClick={()=>act(()=>api.researchProjectAction(project.id,'state',{state:project.state==='PAUSED'?'BASELINE_ANALYSIS':'PAUSED'}))}>{project.state==='PAUSED'?'Resume':'Pause'}</button><button className="mini-btn" disabled={busy} onClick={()=>act(()=>api.researchProjectAction(project.id,'state',{state:'ARCHIVED'}))}>Archive</button></>}</div></article>
 <article className="insight-panel"><h4 className="font-semibold">Dataset access</h4>{project.datasets.map(d=><div key={d.id} className="mt-3 text-sm"><strong>{d.symbols.join(', ')} / {d.start} - {d.end}</strong><p>{d.state}</p>{['LOCKED_HOLDOUT','FUTURE_OOS'].includes(d.state)&&<><p className="text-xs mt-1">{WARNING} Approval is permanent, even if inspection is not completed.</p><button className="mini-btn mt-1" disabled={busy||project.state==='ARCHIVED'} onClick={()=>{if(confirm(WARNING))act(()=>api.researchProjectAction(project.id,`datasets/${d.id}/approve`,{acknowledgement:'This dataset will no longer be unseen'}));}}>Approve holdout inspection</button></>}</div>)}</article>
 <article className="insight-panel"><h4 className="font-semibold">Deterministic evidence</h4>{Object.entries(project.analyses).map(([id,a])=><div key={id} className="mt-3"><strong>Run {id} / N {a.summary.n} / Total R {a.summary.total_r==null?'Unavailable':a.summary.total_r.toFixed(2)}</strong><p className="text-xs muted">{a.warnings.join(' ')}</p><ResearchEvidence analysis={a}/></div>)}<details className="mt-3"><summary>Breakdowns, replacement trades, lineage and audit history</summary><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify({analyses:project.analyses,comparison:project.comparison,lineage:project.lineage,events:project.events},null,2)}</pre></details></article><ResearchLoop key={project.id+"loop"} project={project} onChange={()=>{setHypothesisRevision(n=>n+1);setTrialRevision(n=>n+1);}}/><ResearchCommittee key={project.id+":"+hypothesisRevision} project={project} onPreregister={()=>setHypothesisRevision(n=>n+1)}/><ResearchHypotheses key={project.id+":"+hypothesisRevision} project={project} onTrialApproved={()=>setTrialRevision(n=>n+1)}/><ResearchTrials key={project.id} project={project} revision={trialRevision}/><ResearchCandidates key={project.id+"candidates"} project={project} revision={trialRevision} onValidationApproved={()=>act(()=>api.researchProject(project.id))}/></>}
 </section>;
}
