import {useEffect,useState} from 'react';
import ResearchDecision from './ResearchDecision.jsx';
import {api} from '../../api/client';
const ACK='Freeze this development candidate without consuming holdout data';
const number=n=>n==null?'Unavailable':Number(n).toFixed(2);
export default function ResearchCandidates({project,revision=0,onValidationApproved}){
 const [trials,setTrials]=useState([]),[items,setItems]=useState([]),[choice,setChoice]=useState(''),[report,setReport]=useState(null),[reason,setReason]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true,timer;const poll=async()=>{try{const [t,c]=await Promise.all([api.researchTrials(project.id),api.researchCandidates(project.id)]);if(!alive)return;setTrials(t.items);setItems(c.items);if(t.items.some(t=>t.status==='ACTIVE'))timer=setTimeout(poll,2500);}catch(e){if(alive)setError(e.message);}};poll();return()=>{alive=false;clearTimeout(timer);};},[project.id,revision,busy]);
 const selected=()=>{const [trial_id,cell_index]=choice.split('/');return {trial_id,cell_index:Number(cell_index)};};
 const assess=async()=>{setBusy(true);setError('');setReport(null);try{setReport(await api.researchProjectAction(project.id,'candidates/assess',selected()));}catch(e){setError(e.message);}finally{setBusy(false);}};
 const freeze=async()=>{setBusy(true);setError('');try{await api.researchProjectAction(project.id,'candidates',{...selected(),reason,acknowledgement:ACK});setConsent(false);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const options=trials.filter(t=>t.status==='COMPLETED'&&t.control_parity===true).flatMap(t=>t.cells.filter(c=>c.role==='variant').map(c=>({key:`${t.id}/${c.index}`,label:`${t.hypothesis.description} / cell ${c.index} / run ${c.run_id}`})));
 return <article className="insight-panel"><h4 className="font-semibold">Candidate robustness and freezing</h4><p className="text-sm muted mt-2">Inspect the tested neighborhood, periods and lost winners before selecting a candidate. Freezing preserves its configuration and evidence and stops the research loop. It does not approve holdout use or promote the strategy.</p>{error&&<p role="alert">{error}</p>}
 <label className="block mt-3">Completed development variant<select className="input" aria-label="Candidate development variant" value={choice} onChange={e=>{setChoice(e.target.value);setReport(null);setConsent(false);}}><option value="">Select a variant</option>{options.map(o=><option key={o.key} value={o.key}>{o.label}</option>)}</select></label><button className="mini-btn mt-2" disabled={busy||!choice||project.state!=='BASELINE_ANALYSIS'} onClick={assess}>Inspect candidate robustness</button>
 {report&&<section className="mt-3"><p>N {report.summary.n} / Avg R {number(report.summary.average_r)} / Total R {number(report.summary.total_r)} / {report.verdict}</p><ul className="text-sm muted list-disc pl-5">{report.warnings.map(w=><li key={w}>{w}</li>)}</ul><div className="overflow-x-auto mt-3"><table className="text-sm w-full text-left"><thead><tr>{['Parameter','Side','Value','N','Avg R','Total R'].map(h=><th className="p-2 whitespace-nowrap" key={h}>{h}</th>)}</tr></thead><tbody>{report.neighbor_coverage.map(n=>{const row=report.neighbors.find(r=>r.parameter===n.parameter&&r.side===n.side);return <tr key={n.parameter+n.side}><td className="p-2">{n.parameter}</td><td className="p-2">{n.side}</td><td className="p-2">{n.tested?n.value:'Not tested'}</td><td className="p-2">{row?.summary.n??'-'}</td><td className="p-2">{number(row?.summary.average_r)}</td><td className="p-2">{number(row?.summary.total_r)}</td></tr>;})}</tbody></table></div><details className="mt-3"><summary>Periods, winner retention, concentration and cost limitations</summary><pre className="text-xs max-h-96 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(report,null,2)}</pre></details><label className="block mt-3">Candidate rationale<textarea className="input" maxLength={4000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="block text-sm mt-2"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Freeze this development candidate; stop autonomous research without consuming holdout data.</label><button className="mini-btn mt-2" disabled={busy||!consent||!reason.trim()||project.state!=='BASELINE_ANALYSIS'} onClick={freeze}>Freeze candidate</button></section>}
 {items.map(c=><details className="mt-3" key={c.id}><summary>Run {c.run_id} / {c.state} / development candidate</summary><p className="text-sm mt-2">{c.reason}</p><ResearchDecision project={project} candidate={c} onValidationApproved={onValidationApproved}/><p className="text-xs muted">Frozen source, configuration and result fingerprint. Validation requires a separate dataset-specific approval.</p><pre className="text-xs max-h-96 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(c,null,2)}</pre></details>)}
 </article>;
}
