import ResearchManager from './ResearchManager.jsx';
import ResearchSandbox from './ResearchSandbox.jsx';
import ResearchRegimes from './ResearchRegimes.jsx';
import {useEffect,useState} from 'react';
import {api} from '../../api/client';
import ResearchSimplification from './ResearchSimplification.jsx';
import ResearchCosts from './ResearchCosts.jsx';
import ResearchValidation from './ResearchValidation.jsx';
const ACK='Record this research decision; it does not authorize live trading';
const FIELDS=[['periods','Period consistency'],['winner_retention','Winner retention and changed paths'],['parameter_sensitivity','Parameter neighborhood'],['costs_and_regimes','Costs and market regimes'],['complexity_and_limitations','Complexity, missing checks and limitations']];
export default function ResearchDecision({project,candidate,onValidationApproved}){
 const [record,setRecord]=useState(null),[validation,setValidation]=useState(null),[loaded,setLoaded]=useState(false),[revision,setRevision]=useState(0),[kind,setKind]=useState('REJECTED'),[reason,setReason]=useState(''),[review,setReview]=useState({}),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true,timer;const poll=async()=>{try{const [d,v]=await Promise.all([api.researchDecisions(project.id),api.researchValidations(project.id)]);if(!alive)return;setRecord(d.items.find(x=>x.candidate_id===candidate.id)||null);const current=v.items.find(x=>x.candidate_id===candidate.id);setValidation(current||null);setLoaded(true);if(current?.status==='ACTIVE')timer=setTimeout(poll,2000);}catch(e){if(alive)setError(e.message);}};poll();return()=>{alive=false;clearTimeout(timer);};},[project.id,candidate.id,revision]);
 const canAccept=validation?.status==='COMPLETED'&&validation.verdict==='VALIDATION_PASS';
 const submit=async()=>{setBusy(true);setError('');try{const value=await api.researchProjectAction(project.id,`candidates/${candidate.id}/decision`,{decision:kind,reason,review:kind==='ACCEPTED_FOR_RESEARCH'?review:null,acknowledgement:ACK});setRecord(value);setConsent(false);}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <section className="mt-3">{error&&<p role="alert">{error}</p>}{!record&&<ResearchValidation project={project} candidate={candidate} onApproved={async()=>{setRevision(n=>n+1);await onValidationApproved?.();}}/>}
 <ResearchManager project={project} candidate={candidate}/><ResearchCosts project={project} candidate={candidate} decided={!!record}/><ResearchSimplification project={project} candidate={candidate} decided={!!record}/><ResearchRegimes project={project} candidate={candidate} decided={!!record}/><h5 className="font-semibold mt-3">Research decision</h5><p className="text-xs muted">Acceptance means a documented research candidate, not live-trading readiness. Missing robustness checks remain limitations. A validation pass alone does not record acceptance. Final decisions cannot be overwritten.</p>
 {record?<><p className="mt-2 font-semibold">{record.decision}</p><p className="text-sm">{record.request.reason}</p>{validation&&<details className="mt-2"><summary>Saved validation evidence</summary><pre className="text-xs max-h-96 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(validation,null,2)}</pre></details>}<details className="mt-2"><summary>Decision, reviewed evidence and limitations</summary><pre className="text-xs max-h-96 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(record,null,2)}</pre></details></>:<><label className="block mt-2">Decision<select aria-label="Candidate research decision" className="input" value={kind} onChange={e=>{setKind(e.target.value);setConsent(false);}}><option value="REJECTED">Reject candidate</option><option value="ACCEPTED_FOR_RESEARCH" disabled={!canAccept}>Accept for further research (passing validation required)</option></select></label>{!canAccept&&<p className="text-xs muted">Acceptance is unavailable until validation completes with a pass and its evidence is reverified.</p>}<label className="block mt-2">Decision rationale<textarea className="input" maxLength={4000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{kind==='ACCEPTED_FOR_RESEARCH'&&FIELDS.map(([key,label])=><label className="block mt-2" key={key}>{label}<textarea className="input" maxLength={2000} value={review[key]||''} onChange={e=>setReview(r=>({...r,[key]:e.target.value}))}/></label>)}<label className="block mt-2 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Record this final research decision; it does not authorize live trading.</label><button className="mini-btn mt-2" disabled={!loaded||busy||!consent||!reason.trim()||project.state!=='BASELINE_ANALYSIS'||validation?.status==='ACTIVE'||(kind==='ACCEPTED_FOR_RESEARCH'&&(!canAccept||FIELDS.some(([k])=>!review[k]?.trim())))} onClick={submit}>Record research decision</button></>}
 <ResearchSandbox project={project} candidate={candidate}/></section>;
}
