import {useEffect,useState} from 'react';
import {api} from '../../api/client';
const value=n=>n==null?'Unavailable':Number(n).toFixed(2);
export default function ResearchTrials({project,revision=0}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;let timer;const poll=async()=>{try{const r=await api.researchTrials(project.id);if(!alive)return;setData(r);if(r.items.some(t=>t.status==='ACTIVE'))timer=setTimeout(poll,1500);}catch(e){if(alive)setError(e.message);}};poll();return()=>{alive=false;clearTimeout(timer);};},[project.id,project.state,revision,busy]);
 const action=async(id,command)=>{setBusy(true);setError('');try{await api.researchProjectAction(project.id,`trials/${id}/${command}`,{});setData(await api.researchTrials(project.id));}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <article className="insight-panel"><h4 className="font-semibold">Approved development trials</h4><p className="text-xs muted">A fresh control must reproduce the baseline before variants run. The backend continues through approved cells while this page is closed. No holdout use, automatic winner or strategy promotion.</p><p className="text-sm mt-2">Reserved simulations: {data?.reserved_runs??0} / {data?.budget.max_trial_runs??80}, including controls and retries.</p>{error&&<p role="alert">{error}</p>}
 {data?.items.map(t=><details className="mt-3" key={t.id} open={t.status==='ACTIVE'}><summary>{t.hypothesis.description} / {t.status} / {t.cells.filter(c=>c.status==='COMPLETED').length} of {t.cells.length} cells</summary><p className="text-xs mt-2">Control parity: {t.control_parity===true?'Verified':t.control_parity===false?'Failed':'Pending'} / {t.verdict}</p>{t.error&&<p role="alert">{t.error}</p>}<div className="ui-toolbar mt-2">{t.status==='ACTIVE'&&<button className="mini-btn" disabled={busy} onClick={()=>action(t.id,'pause')}>Pause trial</button>}{t.status==='PAUSED'&&<button className="mini-btn" disabled={busy||project.state!=='BASELINE_ANALYSIS'} onClick={()=>action(t.id,'resume')}>Resume trial</button>}{['ACTIVE','PAUSED'].includes(t.status)&&<button className="mini-btn" disabled={busy} onClick={()=>action(t.id,'cancel')}>Cancel trial</button>}</div><div className="overflow-x-auto mt-3"><table className="text-sm w-full text-left"><thead><tr>{['Cell','State','Run','N','Avg R','Total R','Removed winners','Removed large winners','Introduced'].map(h=><th key={h} className="p-2 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{t.cells.map(c=><tr key={c.index}><td className="p-2 whitespace-nowrap">{c.role} {c.index}</td><td className="p-2 whitespace-nowrap">{c.status}</td><td className="p-2">{c.run_id??'-'}</td><td className="p-2">{c.comparison?.child.summary.n??'-'}</td><td className="p-2">{value(c.comparison?.child.summary.average_r)}</td><td className="p-2">{value(c.comparison?.child.summary.total_r)}</td><td className="p-2">{c.comparison?.removed_winners.n??'-'}</td><td className="p-2">{c.comparison?.removed_large_winners.n??'-'}</td><td className="p-2">{c.comparison?.introduced.n??'-'}</td></tr>)}</tbody></table></div><details className="mt-2"><summary>Exact cells, provenance and comparison evidence</summary><pre className="text-xs max-h-96 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(t,null,2)}</pre></details></details>)}
 </article>;
}
