import {useEffect,useState} from 'react';
import {api} from '../../api/client';
const ACK='Run declared regime windows on development data; labels are my assumptions and windows are independent';
const empty=()=>({name:'',start:'',end:'',definition:'',evidence_source:''});
const fmt=n=>n==null?'Unavailable':Number(n).toFixed(2);
export default function ResearchRegimes({project,candidate,decided=false}){
 const [report,setReport]=useState(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[rows,setRows]=useState([empty()]),[reason,setReason]=useState(''),[consent,setConsent]=useState(false);
 useEffect(()=>{let alive=true,timer;const poll=async()=>{try{const r=await api.researchRegimes(project.id,candidate.id);if(!alive)return;setReport(r);setLoaded(true);if(r?.status==='ACTIVE')timer=setTimeout(poll,1500);}catch(e){if(alive)setError(e.message);}};poll();return()=>{alive=false;clearTimeout(timer);};},[project.id,candidate.id,busy]);
 const submit=async()=>{setBusy(true);setError('');try{await api.researchProjectAction(project.id,`candidates/${candidate.id}/regimes`,{scenarios:rows,rationale:reason,acknowledgement:ACK});setConsent(false);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const action=async(command)=>{setBusy(true);setError('');try{await api.researchProjectAction(project.id,`trials/${report.trial_id}/${command}`,{});}catch(e){setError(e.message);}finally{setBusy(false);}};
 const change=(i,key,value)=>{setRows(rows.map((r,j)=>j===i?{...r,[key]:value}:r));setConsent(false);};
 const valid=rows.every(r=>Object.values(r).every(v=>v.trim())&&r.start<=r.end);
 return <details className="mt-3"><summary>Development regime robustness</summary><p className="text-xs muted mt-2">Declare non-overlapping windows within the frozen development dates. Each runs baseline and candidate through the engine on identical data after a full candidate control. Labels require a definition and evidence source; Ledger does not infer regimes from returns. Windows reset capital and positions and close at their end. Do not combine them into portfolio performance. This consumes the shared run budget.</p>{error&&<p role="alert">{error}</p>}
 {report?<><p className="mt-2">{report.status} / Control: {report.control_parity===true?'Verified':report.control_parity===false?'Failed':'Pending'}</p><div className="ui-toolbar mt-2">{report.status==='ACTIVE'&&<button className="mini-btn" disabled={busy} onClick={()=>action('pause')}>Pause regime trial</button>}{report.status==='PAUSED'&&<button className="mini-btn" disabled={busy||decided||project.state!=='BASELINE_ANALYSIS'} onClick={()=>action('resume')}>Resume regime trial</button>}{['ACTIVE','PAUSED'].includes(report.status)&&<button className="mini-btn" disabled={busy} onClick={()=>action('cancel')}>Cancel regime trial</button>}</div><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Window / variant','State','N','Average R','Total R','PF (R)','Win %','MFE R','MAE R'].map(h=><th className="p-2 whitespace-nowrap" key={h}>{h}</th>)}</tr></thead><tbody>{(report.rows||[]).map((r,i)=><tr key={i}><th className="p-2 whitespace-nowrap">{r.name}{r.summary?.low_sample?' / Low sample':''}</th><td>{r.status}</td><td>{r.summary?.n??'-'}</td>{['average_r','total_r','profit_factor_r','win_rate_pct','average_mfe_r','average_mae_r'].map(k=><td className="p-2" key={k}>{fmt(r.summary?.[k])}</td>)}</tr>)}</tbody></table></div><p className="text-xs muted">{report.limitation}</p><details><summary>Declared regimes, source and path changes</summary><pre className="text-xs max-h-96 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(report,null,2)}</pre></details></>:decided?<p className="text-xs muted">No regime trial was approved before this final decision.</p>:<>{rows.map((r,i)=><fieldset className="mt-3" key={i}><legend>Regime window {i+1}</legend>{[['name','Regime name'],['start','Start date'],['end','End date'],['definition','Numerical definition / market conditions'],['evidence_source','Evidence source for the classification']].map(([k,label])=><label className="block mt-2" key={k}>{label}<input className="input" type={['start','end'].includes(k)?'date':'text'} value={r[k]} onChange={e=>change(i,k,e.target.value)}/></label>)}{rows.length>1&&<button className="mini-btn mt-2" onClick={()=>{setRows(rows.filter((_,j)=>j!==i));setConsent(false);}}>Remove regime window</button>}</fieldset>)}<button className="mini-btn mt-2" disabled={rows.length>=6} onClick={()=>{setRows([...rows,empty()]);setConsent(false);}}>Add regime window</button><label className="block mt-2">Regime study rationale<textarea className="input" value={reason} onChange={e=>{setReason(e.target.value);setConsent(false);}}/></label><label className="block text-sm mt-2"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Run these development windows; I understand the regime labels and independent-window limitations.</label><button className="mini-btn mt-2" disabled={!loaded||busy||!valid||!reason.trim()||!consent||project.state!=='BASELINE_ANALYSIS'} onClick={submit}>Approve regime robustness trial</button></>}
 </details>;
}
