import {useEffect,useState} from 'react';
import {api} from '../../api/client';
const ACK='Run this frozen candidate on the selected dataset; it will no longer be unseen';
export default function ResearchValidation({project,candidate,onApproved}){
 const [rows,setRows]=useState([]),[dataset,setDataset]=useState(''),[criteria,setCriteria]=useState({minimum_trades:30,minimum_average_r:0,minimum_profit_factor_r:1}),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true,timer;const poll=async()=>{try{const data=await api.researchValidations(project.id);if(!alive)return;setRows(data.items);if(data.items.some(v=>v.status==='ACTIVE'))timer=setTimeout(poll,2000);}catch(e){if(alive)setError(e.message);}};poll();return()=>{alive=false;clearTimeout(timer);};},[project.id,busy]);
 const validation=rows.find(v=>v.candidate_id===candidate.id);
 const approve=async()=>{setBusy(true);setError('');try{await api.researchProjectAction(project.id,`candidates/${candidate.id}/validate`,{dataset_id:dataset,criteria,acknowledgement:ACK});setConsent(false);await onApproved?.();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <section className="mt-3"><h5 className="font-semibold">Candidate-specific validation</h5><p className="text-xs muted">Using this dataset means it will no longer be considered unseen. Approval freezes criteria and reserves baseline + candidate simulations. It remains inspected even if execution fails. A pass is not automatic promotion.</p>{error&&<p role="alert">{error}</p>}
 {validation?<><p className="mt-2">{validation.status} / {validation.verdict}</p>{validation.error&&<p role="alert">{validation.error}</p>}<details><summary>Frozen grant, criteria and results</summary><pre className="text-xs max-h-96 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(validation,null,2)}</pre></details></>:<><label className="block mt-2">Untouched validation dataset<select className="input" aria-label="Candidate validation dataset" value={dataset} onChange={e=>setDataset(e.target.value)}><option value="">Select dataset</option>{project.datasets.filter(d=>['LOCKED_HOLDOUT','FUTURE_OOS'].includes(d.state)).map(d=><option key={d.id} value={d.id}>{d.start} - {d.end} / {d.symbols.join(', ')}</option>)}</select></label><div className="grid gap-2 sm:grid-cols-3">{[['minimum_trades','Minimum trades'],['minimum_average_r','Minimum average R'],['minimum_profit_factor_r','Minimum R profit factor']].map(([key,label])=><label key={key}>{label}<input className="input" type="number" step={key==='minimum_trades'?1:.01} value={criteria[key]} onChange={e=>setCriteria(c=>({...c,[key]:Number(e.target.value)}))}/></label>)}</div><label className="block mt-2 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I approve consuming this dataset for this frozen candidate and fixed criteria.</label><button className="mini-btn mt-2" disabled={busy||!dataset||!consent||project.state!=='BASELINE_ANALYSIS'} onClick={approve}>Approve and run candidate validation</button></>}
 </section>;
}
