import {useEffect,useState} from 'react';
import {api} from '../../api/client';
import {sandboxActive,sandboxApproval} from './researchSandbox';
export default function ResearchSandbox({project,candidate}){
 const [drafts,setDrafts]=useState([]),[runs,setRuns]=useState([]),[choice,setChoice]=useState(''),[control,setControl]=useState('{}'),[parameters,setParameters]=useState('{}'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let alive=true,timer;const refresh=async()=>{try{const [d,r]=await Promise.all([api.researchCodeDrafts(project.id,candidate.id),api.researchSandboxRuns(project.id)]);if(!alive)return;setDrafts(d.items);setRuns(r.items.filter(x=>x.candidate_id===candidate.id));if(r.items.some(sandboxActive))timer=setTimeout(refresh,1500);}catch(e){if(alive)setError(e.message);}};refresh();return()=>{alive=false;clearTimeout(timer);};},[project.id,candidate.id,revision]);
 const act=async(action,payload)=>{setBusy(true);setError('');try{await api.researchProjectAction(project.id,action,payload);setConsent(false);setRevision(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const approve=()=>{try{act(`candidates/${candidate.id}/code-drafts/${choice}/sandbox`,sandboxApproval(control,parameters));}catch(e){setError(e.message);}};
 return <section className="mt-4"><h5 className="font-semibold">Quarantined strategy sandbox</h5><p className="text-sm muted">Generated code runs only in offline Docker. Four checks are reserved from the research budget. The disabled-change control must reproduce this frozen candidate. Results remain development evidence; they never activate a strategy or consume holdout data.</p>
 {error&&<p role="alert">{error}</p>}
 {!drafts.length?<p className="text-sm mt-2">No quarantined drafts for this candidate.</p>:<><label className="block mt-2">Quarantined draft<select className="input" value={choice} onChange={e=>{setChoice(e.target.value);setConsent(false);}}><option value="">Select a draft</option>{drafts.map(d=><option key={d.id} value={d.id}>{d.request.registry_key} / {d.source_sha256.slice(0,12)}</option>)}</select></label>
 <label className="block mt-2">Disabled-change control parameters (JSON)<textarea className="input" value={control} onChange={e=>setControl(e.target.value)}/></label><label className="block mt-2">Candidate parameters (JSON)<textarea className="input" value={parameters} onChange={e=>setParameters(e.target.value)}/></label>
 <label className="block text-sm mt-2"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Approve Docker execution on frozen development data (120-second limit).</label><button className="mini-btn mt-2" disabled={busy||!choice||!consent||runs.some(sandboxActive)||project.state!=='BASELINE_ANALYSIS'} onClick={approve}>Run isolated checks</button></>}
 {runs.map(r=><article key={r.id} className="mt-3"><p className="font-semibold">{r.status} / {r.phase}</p>{r.error&&<p role="alert">{r.error}</p>}{sandboxActive(r)&&<button className="mini-btn" disabled={busy} onClick={()=>act(`sandbox-runs/${r.id}/cancel`,{})}>Cancel isolated run</button>}{r.summary&&<p className="text-sm">N {r.summary.n} / Average R {r.summary.average_r??'Unavailable'} / Control parity {r.control_parity?'passed':'not passed'}</p>}<details><summary>Evidence and Docker provenance</summary><pre className="text-xs max-h-96 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(r,null,2)}</pre></details></article>)}
 </section>;
}
